### ISSUE TITLE
Vehicle explosion while previewing [JNG]

### ISSUE THREAD

**Issue by loxley314** [A3Antistasi/antistasiofficial#102]
Right now, vehicles spawn 10 meters in front of player in the heading of he is looking for:
https://github.com/A3Antistasi/antistasiofficial/blob/master/AntistasiOfficial.Altis/JeroenArsenal/JNG/fn_garage.sqf#L1674
This cause that sometimes vehicles explodes while previewing them. That behaviour cause death of near players/AI next to that vehicles, that happened to me on my Linux DS.

There are 2 commented lines currently in code. That 2 lines avoid this behaviour when are uncommented. Are only applied while a vehicle is previewed. 
https://github.com/A3Antistasi/antistasiofficial/blob/0cfebce208399ec2810cb16a47a5ddb3e422629a/AntistasiOfficial.Altis/JeroenArsenal/JNG/fn_garage.sqf#L1685-L1686

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/commit/14e360dd005741d53cf09f10708f6df7d0a6c2a4 Done, now let's see
