### ISSUE TITLE
SellGears function

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#103]
https://github.com/A3Antistasi/antistasiofficial/blob/0cfebce208399ec2810cb16a47a5ddb3e422629a/AntistasiOfficial.Altis/UI/sellMenu.sqf#L1-L3

which goes here
https://github.com/A3Antistasi/antistasiofficial/blob/0cfebce208399ec2810cb16a47a5ddb3e422629a/AntistasiOfficial.Altis/Functions/fn_createItemDB.sqf#L6-L7

Basically this is not possible considering items are no longer staying in caja inventory, they are in Jeroen Arsenal instead.

I never used this function to be honest so i don't even know if it will work. Anyway i thought it was a good thing to share it here. 

To test this function just remove the comment from this line
https://github.com/A3Antistasi/antistasiofficial/blob/0cfebce208399ec2810cb16a47a5ddb3e422629a/AntistasiOfficial.Altis/Functions/fn_init_hq.sqf#L29

**Comment by loxley314** [comment]
I think JNG it's not a problem to use this feature. I just tried on 1.7.17F, just need to move items that want to sell into crate, and works.
Just selled a F2000 without ammo by 30.5$
Where is the price list?

**Comment by StefArma** [comment]
Oh interesting!

It's here
https://github.com/A3Antistasi/antistasiofficial/blob/5cc05436e97d079a73a4534a71df8be63ca920ae/AntistasiOfficial.Altis/Functions/fn_sellGear.sqf#L25-L32

**Comment by StefArma** [comment]
How about if we increase the basic price to 100 ? Even airsoft equipment averagely more than 100€ per piece. 

The problem is sellMenu.sqf by now there is only defined the category weapons... this make magazines the same price of a weapon... infact mags should start from 5€ baseprice or even less.

**Comment by StefArma** [comment]
Discontinued
