### ISSUE TITLE
Make HR -1 when players die in MP

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/antistasiofficial#11]
Make the Antistasi great again! )))

**Comment by StefArma** [comment]
Then noobs will influence too much the campaign as recruit AI is restricted to members to avoid HR waste

**Comment by AlexTriada** [comment]
Ok, make this only for members or if the membership is disabled- for all players

**Comment by zalexki** [comment]
Agree with @StefArma, this is too hard on public servers.

Feel free to fork and adapt to your needs.
