### ISSUE TITLE
Personal Garage Issues

### ISSUE THREAD

**Issue by eagledude4** [A3Antistasi/antistasiofficial#115]
Forgot to tag as a BUG

`21:06:53 Warning Message: Picture \a3\ui_f\data\gui\rsc\rscdisplaysinglemission\source\backup\large_64x64\locked_ca.paa not found
21:06:53 Error in expression <[true] spawn garage>
21:06:53   Error position: <garage>
21:06:53   Error Undefined variable in expression: garage`

Attempting to activate the "Personal Garage" action on flags will produce the above issue.

**Comment by StefArma** [comment]
Ofcourse, there is no such Personal Garage anymore.. check the vebicle box

**Comment by eagledude4** [comment]
So when a feature is removed, the code just gets broken, good to know
