### ISSUE TITLE
Personal Garage in NATO airports

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/antistasiofficial#118]
file **createNATOaerop.sqf**
this lines is active
line 52:   [_flag,**"garage"**] remoteExec ["AS_fnc_addActionMP"];
line 199:   [_flag,**"garage"**] remoteExec ["AS_fnc_addActionMP"];

file **fn_addActionMP.sqf**
line 25:
case **"garage"**: {
		if (isMultiplayer) then {
			_object addAction [localize "STR_ACT_PERSGARAGE", {[true] spawn garage},nil,0,false,true,"","(isPlayer _this) and (_this == _this getVariable ['owner',objNull])"]
		} else {
			_object addAction ["FIA Garage", {[false] spawn garage},nil,0,false,true,"","(isPlayer _this) and (_this == _this getVariable ['owner',objNull])"]
		};

**Comment by StefArma** [comment]
Closing for now
