### ISSUE TITLE
Arsenal access from Vehicle

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#119]
Adding limited items to inventory vehicle move a weird number of them.
There are 10 grenades, instead of adding one it add 6 and substract sometime the same amount sometime a different number

It works fine with unlimited indeed.

Fixing this function would allow using the sellgears (retrive from arsenal with a vehicle, garage vehicle, items are added to caja inventory = ready for sellgears https://github.com/A3Antistasi/antistasiofficial/issues/103

**Comment by StefArma** [comment]
Is this solved by this? https://github.com/A3Antistasi/antistasiofficial/commit/37548967ca6e43871ff5419cc65ab223ad68c0e5

**Comment by Sparker95** [comment]
Yes.
The cause was this: it executed code on every client's computer. So if you had 6 clients connected, it would substract 6 grenades.
