### ISSUE TITLE
Greenfor Altis, outpost respawn after clear

### ISSUE THREAD

**Issue by zverofaust** [A3Antistasi/antistasiofficial#120]
Outpost at Synneforos, near the northwestern-most Power Plant, respawns when I load my Persistent Save. 

I cleansed this "hidden" outpost and moved my HQ nearby. Next day I loaded game, got in a tank, started driving and boom, killed by respawned TOW launcher. 

However upon "re-cleansing" the outpost there is no "Outpost Cleansed" message (or counterattack) so it isn't a proper spawning of the outpost, though all of its assets and troops respawned.

This was using RHS.

**Comment by StefArma** [comment]
It's never a good idea to place HQ within 1km of any place(town or militarized) because the enemy can counterattack or just send patrols.

Anyway i'll dig into it

**Comment by StefArma** [comment]
Oh ok i just realized you were talking about a CSAT hilltop... actually they never did this issue... i'm trying it now

**Comment by StefArma** [comment]
Actually you should  see "CSAT emplacement destroyed" otherwise it's not considered destroyed

**Comment by StefArma** [comment]
To me it's clear after i persistent load, tested also without inidibi2

**Comment by zverofaust** [comment]
I'm using RHS Green so it's a USMC AA location with M6A1 etc. The first time I cleared it I did get the message, but it stills respawns, and re-clearing it doesn't give the message anymore. Hmmmm.

**Comment by StefArma** [comment]
Green version is no longer supported,  forgot to remove the files. I can't keep them all up
