### ISSUE TITLE
POW Rescue at Outposts/Bases is kind of daft

### ISSUE THREAD

**Issue by zverofaust** [A3Antistasi/antistasiofficial#122]
The only way to realistically rescue POWs at a Base/Outpost is to take the entire outpost. This seems kind of  a little harsh and an astronomical step up in difficulty from Refugee Evac missions; the Evac mission is a solid early-game mission that gives good rewards early game, but POW Rescues are impossible early game at bases.

At outposts, particularly ones where counterattack is done by helicopter, often reinforcements will arrive before you're even done doing liberate action on all the POWs, and suddenly you have ~40 enemy troops ziplining down around you. 

It would be nice if POW missions didn't occur until later-game when players are actually realistically capable of attacking bases and dealing with counter attacks, or they took place outside of bases. Outposts would be an ideal location except for the above-mentioned reinforcements which arrive far too quickly to escape.

**Comment by StefArma** [comment]
Missions are more choices rather than orders.. even a Traitor mission is difficult at the beginning and you'd better ignore it if you don't feel you're ready to complete it successfully.

Reinforcements can be easily distracted, leave some AI 300m away to shoot them upon arrival, probably your AI will die but you have time for looting/reorganizing on the spot.

**Comment by zverofaust** [comment]
That's true, but speaking from perspective of singleplayer, sometimes Rescue missions are very very important to boost your HR to get some AI squadmates, and we rely on those early game missions to be able to have squads of AI since we play singleplayer.

**Comment by StefArma** [comment]
Then this point to https://github.com/A3Antistasi/antistasiofficial/issues/49
