### ISSUE TITLE
 A lot of workers spawning in factories

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/antistasiofficial#131]
Workers in the factories, they appear more than necessary, once I observed how about 100+ bots-workers went in the factory at Atira. The similar problem already was, now she has again returned(

**Comment by AlexTriada** [comment]
The similar problem already was, now she has again returned?

**Comment by AlexTriada** [comment]
Update, workers are spawning when you are adding units from garrisons menu, when you leave this area more then 1200 m and back  - all normal

**Comment by AlexTriada** [comment]
Pay attention to this problem, pls, it seems to me very important, in the issue of server performance!

**Comment by StefArma** [comment]
Agree

**Comment by StefArma** [comment]
Fixed! https://github.com/A3Antistasi/antistasiofficial/pull/219/commits/37c1d62c6a2587a81e8890a639bb2a0333bbc24b
