### ISSUE TITLE
 Anomalous zone between Poliakko, Alikampos, Katalaki, Neohori

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/antistasiofficial#132]
There are places on Altis where there is something unbelievable with the spawn dozens of cars appear on the roads, and dozens of patrols are generated, although the place seems not to be the most crowded.
Reproduction steps:
Go to zone between Poliakko, Alikampos, Katalaki, Neohori and you'll see the problem

**Comment by StefArma** [comment]
you've civi % too high

**Comment by AlexTriada** [comment]
NO!!! 0%!!!

**Comment by AlexTriada** [comment]
@StefArma "you've civi % too high" you dont understanding me, my civil % is 0%

**Comment by AlexTriada** [comment]
Reproduction steps:
Go to zone between Poliakko, Alikampos, Katalaki, Neohori and you see the problem

**Comment by AlexTriada** [comment]
maybe this help I hope
https://github.com/A3Antistasi/antistasiofficial/commit/3ce5e1029c8bf4daac14337731f4250b192e5fad
