### ISSUE TITLE
 Hell for server administrators.

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/antistasiofficial#133]
Every time after server restart, I need to go to the server, select in your poor tablet - disable membership, and click on the start, otherwise any moron who enters the server can just close the tablet by pressing escape, and since by default the membership is enabled, game will not give anyone a commander, after this moron leaves the server - **campaign NEW**, **commander NONE**  -- its **the HELL**!
I hesitated to explain to my players how to properly launch the mission, when I'm far away and can not run it!!!

**Comment by AlexTriada** [comment]
A good way to make a mission with a normal restart is to put all the initial settings in the parameters at the start of the mission, and there in the parameters, make a setting that would allow the mission to boot without a tablet and select game settings by the first fool player who logged onto the server.

**Comment by AlexTriada** [comment]
Let by default your poor tablet is displayed. If you make a parameter that allows you to load the game as I want, without a tablet, I will write it through the config file and there are no problems.

**Comment by StefArma** [comment]
How about: escape = continue campaign?

**Comment by AlexTriada** [comment]
Good but not so good, problem with Server membership and CommSwitch too, i have a public server and i need, that nobody can set the server options exept me

**Comment by AlexTriada** [comment]
this tablet is not needed at all for me in a dedicated server, and i think not only for me

**Comment by FlyingVolvo** [comment]
Are you aware of the fact that we have INIDBI2 support for your saves? You should really be using this feature, if you're running a public server. Also, your issue is not very descriptive. If you could start by clarifying what you want, and potentially how to implement it, it'd be much more constructive. Thanks.

**Comment by AlexTriada** [comment]
??? Volvo,
i don’t have problem with my saves, thanks, I describe the problem very clearly, if you don’t understand ... think another one. And what is not so much constructive? You don’t have the solution, am I wrong? You just have bla bla bla and don’t want to help me? Yes?

**Comment by AlexTriada** [comment]
My saves are backup every 10 minutes, and I don’t have a problem with the saves, I don’t understand at all what about the saves do you want to say to me?

**Comment by AlexTriada** [comment]
Problem is with autostart the mission with continue the campaign

**Comment by AlexTriada** [comment]
Key word is auto, without any need action.

**Comment by AlexTriada** [comment]
How about: escape = continue campaign - and I must every time to go to the server - it is you Idea? You don’t help me at all(((

**Comment by AlexTriada** [comment]
Let by default your poor tablet is displayed.
In the parameters of the mission, make three new ones:

enable CommSwitch - default yes
enable server membership - default yes
automatic start from save - default no

automatic start means that poor tablet is not displayed and campaign will be starting from the save with settings above.

**Comment by AlexTriada** [comment]
The people, the mission is becoming more popular and popular, you have done a great job for this, it seems to me that ignoring the problem is not our method

**Comment by f1af** [comment]
patch for fix this problem (in oler version of antistasi)
https://github.com/f1af/Antistasi-non-official/commit/abb16bd26c2caa6af777e797c369f6797cb39b11

**Comment by StefArma** [comment]
Hi i got it.. working on Thanks for all hints

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/pull/142

**Comment by AlexTriada** [comment]
hm... 
esc = load from save, start mission = load from save, membership settings saving in the save?

**Comment by StefArma** [comment]
no, it's not live yet, but if you take a look, it will be all behind parameters

If you don't change parameters the mission starts by itself by continuing the previous save.

**Comment by AlexTriada** [comment]
Thank you all) I am happy!

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/commit/4b83074fc95f3a89d4a29da99e5eba77fad4ba1b
