### ISSUE TITLE
Not being taken to HQ location when loading Persistent Save

### ISSUE THREAD

**Issue by zverofaust** [A3Antistasi/antistasiofficial#140]
This issue started creeping up over the past week, as subsequent loads of my Persistent Save would, more and more frequently, not bring me to my HQ but leave me stranded in the default start location.

Essentially, when I select Yes to load previous game after loading into the scenario, more often than not I'll be left stranded at the default start location while my HQ is moved to the proper spot. I can't figure out what a cause might be as it seems to happen randomly, at first it only happened every so often but now it's at least 3/4 of the time. Given that the frequency of it is getting higher and higher it might have something to do with compounding issues in the persistent save. I also have a pretty shit computer that takes a long time to load things so that might have something to do with it.

It's not game-breaking per se, as I can fast travel to my HQ, but obviously it's frustrating!

**Comment by StefArma** [comment]
Need more details:
- SP or hosting or dedicated server?
- persistent save or +inidibi2 ?

We have that issue on official server and it was due to the savegame. Moving HQ fixed it. 
It looks it happened because people were interacting with HQ assets while i was thinking on HQ initial position.

**Comment by IrLED** [comment]
That is the bug @StefArma and me faced several days ago. There is possible fix already on git.
Supposedly it should happen for non-JIT players with the server on network (remote).
My theory what might cause that: first teleport occurs to firepit (world object). When the save is loaded different physical entities are repositioned in the world. When the object is far away from your initial world position, its position changes are sent with delay (network optimization, i dont have proof, but empirically it is so, when you watch the markers of distant vehicles - they jump). Also the save can contain some garbage around the base (sandbags, lanterns etc). During the load-repositioning there is the spike in the info needed to transmit, and, i think, priority kicks in (so maybe firepit position is delayed). Also markers seem to have higher transfer priority then distant physical objects. So i changed the initial teleportation point to base marker, not firepit. Supposedly that should fix the behavior.

**Comment by IrLED** [comment]
The effect of data actualization might be observer this way: you start the game and teleport to default (wrong position) you see pit, whiteboard, Petros. You enter to spectator mode and position camera to the right HQ position - you see firepit, flag, board, Petros (data is actualized to the player for the objects near camera position). You exit spectator mode, and see that previously visible petros-pit-flagpole are gone (not actually gone, but your local world copy is synchronized with server world state). So it's sort of initial desync

**Comment by IrLED** [comment]
That is not proven, but empirically it is the most probable cause of such behavior.

**Comment by IrLED** [comment]
Supposedly is fixed by #137.
Closing for now
