### ISSUE TITLE
USMC resupply drop glitching through the ground

### ISSUE THREAD

**Issue by owner65** [A3Antistasi/antistasiofficial#143]
Had this happening 3 times on my clan server. These happened in a row as i wanted to see if anything goes wrong with the drop but i couldn't see anything wrong with it. I'm gonna try and do this again and post some images here.
![20171202125311_1](https://user-images.githubusercontent.com/34184987/33515646-d445fd68-d76e-11e7-8325-fbbcf1038813.jpg)

**Comment by StefArma** [comment]
Actually it's happening on 1.7 too... so this might be because a BIS update http://steamcommunity.com/workshop/filedetails/discussion/378941393/1621724915796373687/

**Comment by StefArma** [comment]
is this still happening? it never happen to me!

**Comment by owner65** [comment]
no clue as i have not been activlly playing antistasi or arma as of late.

**Comment by StefArma** [comment]
the question was indeed to everyone ;)

**Comment by StefArma** [comment]
Looks not happening anymore
