### ISSUE TITLE
The enemy base keeps respawning/resetting OR the qrf just spawns in at their target.

### ISSUE THREAD

**Issue by owner65** [A3Antistasi/antistasiofficial#144]
Had this happen twice in a row on my own server (HC4 version) at the base just above Lakka. Seems that when we grab the flag from there the enemy AI starts to spawn in and couple of tanks/apc/ifv come slightly later. Also this happened on the official server (HC5 update) when me and Viktor took the salt lake airfield. Also notable was that the reward box only contained vanilla weapons (i.e mk200 and a some MXs).

**Comment by StefArma** [comment]
Is this still a thing?

**Comment by colmaniac** [comment]
I had the same too, different Base and on single player.  Base was pretty empty, few garrds in statics.  I hit the Base and took the base flag in a few mins a few secs later the enemy started to spawn in, I managed to spot 3 groups of  troops

**Comment by StefArma** [comment]
Fixed https://github.com/A3Antistasi/antistasiofficial/pull/219
