### ISSUE TITLE
Propaganda leaflet drop bug?

### ISSUE THREAD

**Issue by owner65** [A3Antistasi/antistasiofficial#145]
I have now twice requested a leaflet drop to Poliakko but on both times the mission fails cause of the truck won't spawn in. Though when requesting for another towns like Lakka or Therisa it works fine. Could be just unlucky with the vehicular spawn. I'll keep on requesting till it works hopefully.

**Comment by StefArma** [comment]
What does .rpt says?

**Comment by vodas3** [comment]
I just tried the latest version and it worked just fine. I even tried start mission form far away and hint that there is no mission works as well.

**Comment by StefArma** [comment]
Lack of evidence

**Comment by owner65** [comment]
Couldn't really reply as im in the army now and i did close the server a while ago so i don't have any files to proof fill this claim.

**Comment by StefArma** [comment]
no worries :)
