### ISSUE TITLE
Loss of control in garage

### ISSUE THREAD

**Issue by RHLier** [A3Antistasi/antistasiofficial#148]
After I enter the garage and select any stored vehicle, the game stops responding to any inputs (keyboard and mouse). The game is not frozen, just no inputs are registering. Also selected car did not spawn after click and camera is still looking at garage box.

Game version - 1.7.18
Map was hosted on dedicated server with inidbi2

**Comment by StefArma** [comment]
Hi, read again the release page, if that's not clear enough i'll try to rephrase in another way :) 
https://github.com/A3Antistasi/antistasiofficial/releases

**Comment by RHLier** [comment]
I see. Thanks for answering.
