### ISSUE TITLE
RHS USMC not reinforcing bases upon capture

### ISSUE THREAD

**Issue by JoshDOTPlay** [A3Antistasi/antistasiofficial#153]
Hi,

Upon capturing an enemy base and defending against QRF, the USMC have not sent any garrison units. I don't know if this was a feature removed (I havn't seen it) but I have been lead to believe by friends and forums posts NATO/USMC are meant to send units to garrison any taken bases.

Cheers

**Comment by StefArma** [comment]
NATO garrison was disabled before adding this project to Github.

Reason: 
- up to 60ish units when can be handled maximum 170 AI..
- too strong to defend against not properly working attacks and compared with the low difficulty in base capturing.

It will be reintroduced as an option that activate a NATO mission to garrison the base which require clearing nearby AA threats. This anywya need the completion of Air Control (https://github.com/A3Antistasi/antistasiofficial/pull/134)
