### ISSUE TITLE
VCOM AI 2 intergation

### ISSUE THREAD

**Issue by IrLED** [A3Antistasi/antistasiofficial#156]
VCOM AI 2 (https://forums.bistudio.com/forums/topic/166374-vcom-ai-v20-ai-overhaul)
This is the experiment to move from AI quantity to quality.
The code is in that PR #155.
Thoughts-comments go here

**Comment by IrLED** [comment]
From A3A shoutbox
> **LukeSmith:** so, last night petros had a nervous breakdown and started running everywhere then driving about like a madman in an offroad... had to ziptie him and put him back in hq hahaha
Petros should be disabled for VCOM, at least random waypointing

**Comment by AlexTriada** [comment]
Good idea!  But someone in the mission scripts make the bot siting and outing from the cars

**Comment by StefArma** [comment]
In singleplayer friendly AI looks way stronger than enemies, ofcourse, if you spot for them. (difficulty: skill 1, precision 0.5)

**Comment by IrLED** [comment]
Some rogue AI should be fixed with #159  (e.g. Petros goes for walk)
- Petros
- Devin the "Crazy Irishman"
- Traitor
- corrupt officer
- corrupt civilian
- refugees
- POWs

**Comment by StefArma** [comment]
to keep under observation: NATO reinforcements

**Comment by mnarijnm** [comment]
First of all: sorry for commentating without testing, but: If you call support from NATO or a campplacement, that is also controlled by antistasi script (like roadblock or camps), is that also not in conflict with VCOM?

For the rest. really awesome that you're doing this experiment!

**Comment by VenomSnake1985** [comment]
Playing With VCOM AI enabled has definitely improved my experience playing, enemies squads and patrols are now a real threat, taking a base is a bit harder now, and the enemy in general seen more responsive to being shot at.

**Comment by StefArma** [comment]
Discontinued
