### ISSUE TITLE
The impact of the number of groups on performance

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/antistasiofficial#157]
In ARMA3 there is a limit on the number of groups, as well as the number of units. Why then in garrisons and at enemy points we have a large number of groups (through the group management mode) in each of these groups of 1-2 units, maybe this is the reason for the falls of FPS on the server, in excess of the number of groups, rather than units. There is an opinion that the units are better combined

**Comment by StefArma** [comment]
Good point, i need to investigate how one big group fight against multiple small groups.. then we need to be sure the AI script make them taking different positions because i would hate they all move in file like a snake :)

**Comment by Sparker95** [comment]
Might be an issue indeed. Arma's limit is 288 groups or so, if i'm not wrong. I'm sure we're far from that. The problem is, many AI actions are handled per group rather than per unit, so more groups means more server load by VCOM or UPS.

**Comment by AlexTriada** [comment]
??? Are you ok ??? 288 group??? 150 units - this is practically limit for normal FPS and you say 288 group? You are so wrong, so wrong!

**Comment by AlexTriada** [comment]
Речь идёт не о теоретическом пределе, а о практическом максимальном количестве групп, которое сервер армы в состоянии обработать

**Comment by AlexTriada** [comment]
Зачем тогда вообще нужны безголовые клиенты, если Арма в состоянии обрабатывать групп больше чем ботов, мне даже интересно, из кого эти группы должны состоять? Из кроликов и змей?

**Comment by AlexTriada** [comment]
I find that limit is 144 groups per side - not 288

**Comment by AlexTriada** [comment]
And on the commander I see many ghost group, I think not all groups are deleting from server in some time

**Comment by Sparker95** [comment]
I highly doubt that the mission makes groups with a single soldier. Last time I looked at the code, it didn't do that.
Anyway, just run this in the watch console while in game:
count allGroups;
it should give you the total amount of groups. If you get too many, we can analyze this further.

**Comment by AlexTriada** [comment]
OK
It remains only to understand how many groups affect the performance of the server

**Comment by IrLED** [comment]
Just an observation: at the very start (after the load), there are already 50+ groups and only 2 units (Petros and you)

**Comment by mnarijnm** [comment]
If this is a real problem, there is just 2 groups that can be reduces: patrols and ghost groups (if they exist). The patrols can be reduced to 1 bigger group of a platoon (11 men) or around 6 men. Also if there are many ghost groups, there should be a checker on every 10 min to remove them maybe? Could be activated by the "payment"handler moment

**Comment by Xyaren** [comment]
There is an alternative syntax to create groups that delete themselves when getting empty:
https://community.bistudio.com/wiki/createGroup

**Comment by StefArma** [comment]
There are other things to do first, performance wise. This will eventually help a bit however many functionalities can be lost. closed for now
