### ISSUE TITLE
Players on the back of an open vehicle should not be incognito

### ISSUE THREAD

**Issue by Xyaren** [A3Antistasi/antistasiofficial#162]
Possible Enhancement.

I kinda feel it a bit odd that a full armed group of soldiers sitting in one pickup truck are completely incognito to the enemy.

**Comment by StefArma** [comment]
Agree, that would be nice... just very difficult for me to code

**Comment by Xyaren** [comment]
I think one has to define a list of cargoIndices (https://community.bistudio.com/wiki/getCargoIndex) per vehicle which are "in the open"

Then the check overt-check has to be adapted to use those variables if available.

This would automatically lead to downward compatibility - if no idices defined, the passengers will be incognito by default.

**Comment by wurzel0701** [comment]
There aren´t much vehicles, it would only require the following vehicles

`"C_Offroad_01_F"`
`"C_Van_01_transport_F"`
`"C_Truck_02_transport_F"`
`"C_Truck_02_covered_F"` <= this one discussable, cause you can technically hide under the plane

Would be nice if someone would give me a list of the open seats, then I would provide the code that would do this

**Comment by StefArma** [comment]
the problem is to fit it into undercover loop... if you know how to that i can manually get the number of each vehicle seat to check

**Comment by wurzel0701** [comment]
You don´t have to fit it under the loop I think, the scripts checks the status based on conditions, I just needed to extend these conditions. The loop is not needed, cause you cant change from the inside of the vehicle to the open spaces without exiting it. If you exit or enter the script checks it once and the trick should be done. I could be wrong so, but I already have the code doing this, so you can test it if you want

**Comment by StefArma** [comment]
interesting! i'll check

**Comment by wurzel0701** [comment]
Have you found it? The same forked repo as the supply system, the branch is undercoverCargo
https://github.com/wurzel0701/antistasiofficial/tree/undercoverCargo

**Comment by StefArma** [comment]
Done in develop, soon PR

**Comment by StefArma** [comment]
Continue here

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/issues/323
