### ISSUE TITLE
Static at - metis-m stops reading as hq asset after reload (1.7.18 + )

### ISSUE THREAD

**Issue by shivachirr** [A3Antistasi/antistasiofficial#164]
so ive noticed every time i reload that the static at metis that you by and spawn for statics for defense at least for the hq stop being read after a reload i can put them in garages but they keep staticking up and having to be replaces every time i reload the save

**Comment by zverofaust** [comment]
I've noticed this at outposts/bases etc too. Statics will get saved the FIRST time and will show up on the first persistent load after they're set up, but subsequent saves/loads after that they disappear.

IE: 

- Start game
- Place static somewhere at a base (within 50m etc)
- Persistent save
- Quit and restart and load persistent save
- Statics should be there
- Save again
- Quit and restart and load again
- Statics are now gone

This doesn't always happen. It might have something to do with players manually placing the statics (ie using Move Asset) vs deploying them from backpacks.

**Comment by shivachirr** [comment]
for me they are still there but what happens after the restart thet are no longer moveable. and for the metis they are nolonger counted as a static for the base. but i have seen a few times where that happened

**Comment by StefArma** [comment]
fixed https://github.com/A3Antistasi/antistasiofficial/commit/6a1722930f28663a5990334ecf1c6ed7d0a140c8
