### ISSUE TITLE
Passing AAF Road Patrol recaptures fully-manned FIA Base

### ISSUE THREAD

**Issue by zverofaust** [A3Antistasi/antistasiofficial#165]
I captured the military base near Agglechiori/Kavala and put a garrison of 20 men along with two mortars and some manually-placed statics. As I stood there setting this up, a random road patrol happened to pass by on the main road -- and my base was instantly lost. A few seconds later the ZU23s and HMGs obliterated the patrol and the base was recaptured, but now showed as having 0 men, meaning I just lost 20 HR and a fully manned base to a passing jeep.

**Comment by StefArma** [comment]
Uhmm interesting, just to be sure:

- captured
- placed statics
- back to HQ and garrisoned
- go to base and while there the patrol came and happened what you said.

i'll try to reproduce, quite busy theese days tho

**Comment by zverofaust** [comment]
Actually it also happened when I was away from the base (over 1km) before I'd set up the statics. I was just at my HQ minding my own business when suddenly I lost the base out of nowhere. I'd just checked it and it was still at full garrison when it happened and I was close enough (about 1.5km) that I should've heard fighting. That's when I decided to actually move my HQ next to the base itself, set up some statics and while I was there, that's when the road patrol recaptured it. So it can happen with or without statics and whether or not the player is there.

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/pull/219
