### ISSUE TITLE
Limit Arsenal Gear access

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#166]
Considered that clans which open their server to pubblic might don't wanna see their arsenal reduced because random pick good weapons and die and also on official server there are problems of this sort.

Some ideas:
A) Commander can toggle the reservation of 15 items per category for members only, at anytime, he can remove the limit and let someone who's asking to grab those.
B) Rank thereshold to get access to better weapons, like, if someone just joined FIA why would Petros allow access the main resources?

Option A require the commander to actively watch over this. 
Option B make sense and can be automatized, the problem is that farming is easy untill rank get reworked.

**Comment by VenomSnake1985** [comment]
I think it should be the commanders job to actively keep an eye on the arsenal and what comes out of it, in way th commander should also be keeping an eye on any new players joining the server.

**Comment by StefArma** [comment]
i'll make a commander option for this

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/commit/0012c20eaeb08f5f06857ad38567b816ecd76549#diff-d44b9c83d01d5917364ccbe6528fb712 Done
