### ISSUE TITLE
Loading a box on a pickup is possible if people are in the back

### ISSUE THREAD

**Issue by Xyaren** [A3Antistasi/antistasiofficial#167]

**Comment by StefArma** [comment]
True, as isn't possible to get in cargo seat after box were loaded and unloaded.

**Comment by Sparker95** [comment]
I've added a check for passengers sitting in cargo space prior to loading a cargo crate here.
Also I've tried to fix the passenger seats being locked after unloading stuff. Works fine on my DS.
Tell me if you notice these problems with the logistics script!
As a bonus, we can now load quadbikes on vehicles.
