### ISSUE TITLE
APCs and helicopters becoming immortal after being "fatally" damaged

### ISSUE THREAD

**Issue by MajorJack** [A3Antistasi/antistasiofficial#170]
This bug is NOT related to the Ace update from Dec 21st, it already happened before that update.

Many RHS Apcs (BMP1/2, BMD2 etc.) are not abandoned by their crew after recieving fatal damage, instead the crew stays in, but the apc becomes unresponsive and immortal (tested that by hitting a bmp 2 with 15 rpgs). This happens frequently to APCs from counterattacks after taking a resource, for example. It is also impossible to enter these apcs.

This can also happen to helicopters during the "establish radio station" mission, we had it happen to several helicopters in one mission. They will become unresponsive and hover forever on the same spot.

Possibly related to this issue: 
https://github.com/A3Antistasi/antistasiofficial/issues/58

**Comment by StefArma** [comment]
since they respond to setdamage 1 only, it might be an headlessclient assignement fault. but this is a guess without much evidence at all

**Comment by MajorJack** [comment]
We don't use HC on our server though (at least not yet). I can try it with HCs though and see if that changes anything.

**Comment by StefArma** [comment]
no setdamage 1 = destroy, that means it explode if i set damage 1. 

then if it's happening without HC my toughts were wrong, still i don't know the cause.
Yes, many  RHS vehicles keep the crew in which is usually killed by players by glitching below the vehicle and shooting inside. 

This part of helicopter is stange, it can't fly if crew is dead indeed, but if you kill them the helicopter fall.

**Comment by MajorJack** [comment]
The immortal helicopters happened multiple times during one establish radio station mission, they are very easily reproduceable for me. The helicopters (mi8) get hit with one or several Iglas (also tried 10 missiles from a littlebird), but do not explode. If the crew is killed by the igla explosion, the helicopter will fall to the ground without being exploding and without being usable/capturable, just like the apcs

**Comment by StefArma** [comment]
Looks not happening anymore, reopen if it's needed
