### ISSUE TITLE
Defend Petros mission in early game is ridiculous

### ISSUE THREAD

**Issue by oldspiceland** [A3Antistasi/antistasiofficial#171]
Seriously, multiple attack helicopters when you have HR under 10, no base defenses even remotely being able to be set up, and all because you fail one Kill the Traitor mission is *ridiculous*.

**Comment by StefArma** [comment]
Yes, because you shouldn't fail that mission.

I understand that the description isn't warning enough... Same as powerplant mechanics... Barbolani wanted to make them understood by player who manage to analyze the situation.

**Comment by oldspiceland** [comment]
> Yes, because you shouldn't fail that mission. You'd rather ignore it so that it will just drain some money and HR

Ah, no. I'd rather do more interesting missions with my small group than a really boring one in an inconvenient spot that has been coming up like once an hour since forever. Kill the Traitor is *always* the same. Traitor is in a building in an inconvenient spot in an inconvenient city. You can spot the building because it has a GaZ and a bunch of guys in front of it. Kill Traitor before he gets into GaZ or blow up GaZ. If he gets into GaZ, be prepared to deal with the game's terrible AI pathing as he drives to...nowhere? and after a certain amount of random driving he will despawn and you will have failed the mission.

It's boring, and happens *way* too frequently to have the penalty it has now. I understand the desire to bump up the penalty but my point is *scaling* these attacks that are triggered based on game stage, not getting rid of them. Scale them based on how many KTT missions have been failed, or VMF support. Do something. Having a VMF do an all-out airborne assault on the base is immersion breaking and honestly pretty un-fun. It has nothing to do with me wanting to ignore KTT missions (Though, honestly, I do because I'd rather be doing leaflet drops, bank robberies, POW rescues, outpost attacks, supply recoveries or almost any other mission).

So, the other alternatives I'd suggest to scaling the KTT failure response to be less balls-out crazy all the time is to make KTT really rare to actually match the response level, or making KTT more dynamic/less bland. Sure that's probably gonna make it harder than showing up with a car bomb for the GaZ and mowing down everybody who comes out the door, but at least maybe me and my group would actually be interested in doing this mission again rather than *wanting* to do something else because it's un-fun.

Seriously though, it's not about *wanting* to ignore the mission so it drops HR or money, it's about immersion and fun being totally ruined by the fact that we have HR of 8, no dudes hired, one boring, bland traitor mission fails and the VMF respond with two VMF Airborne QRFs and a CAS helicopter within *seconds* of the traitor mission failing. Again, not asking for it to be removed totally, I'm asking for it to be made more reasonable.

**Comment by MajorJack** [comment]
You do now, that you can just not start the KTT mission and if it fails, it will not reveal your base?
So you can just downright ignore it, just don't get close to it.

Also if you fail it, immediately relocate your base, hence the enemy will no longer know your base position.

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/commit/14ba6d9f1407f34633c27f3b5e9693c4f891fde5
