### ISSUE TITLE
fn_detect_Ace detects ace even when server and client have no ace mod running

### ISSUE THREAD

**Issue by kOepi123** [A3Antistasi/antistasiofficial#173]
Hey,

with the latest ACE updated, one or two days ago,
the RPT lopg says: ACE detected.

Anstistasi version: 1.7.18G

Even though server and client are not running ace, neither are ace components saved to the mission file.
No RPT errors on dedicated server, multiplayer or singleplayer shown.

P.S. I also have some troubles with the ACE logs, I think it is caused by the new ACE / CBA merge.
It results in delayed functions running.

**Comment by kOepi123** [comment]
[MPMissions.zip](https://github.com/A3Antistasi/antistasiofficial/files/1581783/MPMissions.zip)

**Comment by StefArma** [comment]
Yes we're aware of the update, however ACE is working on our server the problem is that all the settings are not loaded properly so it give instadeath to players and enemies, just a bullet :(

**Comment by kOepi123** [comment]
so:` 7:23:04  Mission file: Partistasi_V_101 (__CUR_MP)
 7:23:04  Mission world: Altis
 7:23:04  Mission directory: mpmissions\__CUR_MP.Altis\
 7:23:07 "kO_epi/BIS_fnc_log: [BIS_fnc_preload] ----- Initializing scripts in Partistasi_V_101 -----"
 7:23:07 "kO_epi/BIS_fnc_log: [recompile] recompile BIS_fnc_missionTasksLocal"
 7:23:07 "kO_epi/BIS_fnc_log: [recompile] recompile BIS_fnc_missionConversationsLocal"
 7:23:07 "kO_epi/BIS_fnc_log: [recompile] recompile BIS_fnc_missionFlow"
 7:23:07 "kO_epi/BIS_fnc_log: [preInit] BIS_fnc_feedbackMain (0 ms)"
 7:23:07 "kO_epi/BIS_fnc_log: [preInit] BIS_fnc_missionHandlers (0 ms)"
 7:23:07 "kO_epi/BIS_fnc_log: [preInit] BIS_fnc_storeParamsValues (0 ms)"
 7:23:07 "kO_epi/BIS_fnc_log: [preInit] ""DeltaTime computation started"""
 7:23:07 "kO_epi/BIS_fnc_log: [preInit] BIS_fnc_keyframeAnimation_deltaTime (0 ms)"
 7:23:07 "kO_epi/BIS_fnc_log: [preInit] BIS_fnc_getServerVariable (0 ms)"
 7:23:07 "kO_epi/BIS_fnc_log: [preInit] RHS_fnc_init (0 ms)"
 7:23:07 [112693,4117.43,0,"XEH: PreInit started. v3.5.0.171204"]
 7:23:08 [CBA] (settings) INFO: Loading mission settings file ...
 7:23:08 [ACE] (common) INFO: Parsed Settings Configs [249.0 ms]
 7:23:09 [ACE] (medical) INFO: Extension version: ace_medical: 3.8.4-ef4d289
 7:23:09 [XEH]: One or more children of class All do not support Extended Event Handlers. Fall back to loop.
 7:23:09 [112693,4119.18,0,"XEH: PreInit finished."]
 7:23:09 "kO_epi/BIS_fnc_log: [preInit] CBA_fnc_preInit (1747.07 ms)"
 7:23:22 Setting invalid pitch 0.0000 for L Alpha 1-1:1 REMOTE
 7:23:22 Setting invalid pitch 0.0000 for server
 7:23:22 Setting invalid pitch 0.0000 for HC_comandante
 7:23:22 Setting invalid pitch 0.0000 for L Alpha 1-2:3 REMOTE
 7:23:22 Setting invalid pitch 0.0000 for garrison
 7:23:22 Setting invalid pitch 0.0000 for carreteras
 7:23:22 Setting invalid pitch 0.0000 for spawner
 7:23:22 Setting invalid pitch 0.0000 for roadblocksEnemy
 7:23:22 Setting invalid pitch 0.0000 for L Alpha 1-2:8 REMOTE
 7:23:23 Setting invalid pitch 0.0000 for L Alpha 1-2:9 REMOTE
 7:23:26 Setting invalid pitch 0.0000 for L Bravo 3-5:1 REMOTE
 7:23:29 "kO_epi/BIS_fnc_log: [script] initPlayerLocal.sqf"
 7:23:29 "kO_epi/BIS_fnc_log: [script] initPlayerServer.sqf"
 7:23:29 "kO_epi/BIS_fnc_log: [postInit] BIS_fnc_missionFlow (0.976563 ms)"
 7:23:29 "kO_epi/BIS_fnc_log: [postInit] BIS_fnc_initParams (4.39453 ms)"
 7:23:29 "kO_epi/BIS_fnc_log: [postInit] BIS_fnc_initRespawn (0 ms)"
 7:23:29 "kO_epi/BIS_fnc_log: [postInit] BIS_fnc_keyframeAnimation_init (30.7617 ms)"
 7:23:29 "kO_epi/BIS_fnc_log: [postInit] BIS_fnc_reviveInit (0 ms)"
 7:23:29 [113836,4139.6,0,"XEH: PostInit started. MISSIONINIT: missionName=Partistasi_V_101, missionVersion=53, worldName=Altis, isMultiplayer=true, isServer=false, isDedicated=false, CBA_isHeadlessClient=false, hasInterface=true, didJIP=false"]
 7:23:30 [113836,4139.75,0,"CBA_VERSIONING: cba=3.5.0.171204, ace=3.12.0.29, "]
 7:23:30 [ACE] (common) INFO: ACE is version 3.12.0.29.
 7:23:30 [ACE] (common) INFO: CBA is version 3.5.0.171204 (min required 3.5.0)
 7:23:30 [ACE] (common) INFO: Extension version: ace_break_line: 3.8.4-ef4d289
 7:23:30 [ACE] (common) INFO: Extension version: ace_parse_imagepath: 3.8.4-ef4d289
 7:23:30 [ACE] (common) INFO: Extension version: ace_clipboard: 3.8.4-ef4d289
 7:23:30 [ACE] (common) INFO: Extension version: ace_fcs: 3.8.4-ef4d289
 7:23:30 [ACE] (common) INFO: Extension version: ace_advanced_ballistics: 3.12.0-8ddde18
 7:23:30 String STR_RHS_WEAP_PKTM not found
 7:23:30 String STR_RHS_WEAP_S25 not found
 7:23:30 String STR_RHS_WEAP_S25L not found
 7:23:30 String STR_RHS_FAB100_NAME not found
 7:23:30 String STR_RHS_FAB100_NAME not found
 7:23:30 String STR_RHS_FAB100_NAME not found
 7:23:30 No speaker given for 
 7:23:30 [ACE] (nametags) INFO: TFR Detected.
 7:23:31 [113836,4141.25,0,"XEH: PostInit finished."]
 7:23:31 [ACE] (common) TRACE: 113837 Reading missionConfigFile params: _paramsArray=[0,0,1,1,0,1,0,1,0,2,1,1,5,1,2,300,600,0,1,1,3,1,0,2,2,1,0,1,1,1500,1,1] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:23
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Medical Level, _settingName=ace_medical_level, _settingValue=1 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_medical_level] type not valid [1] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Enable Team Management, _settingName=ace_interaction_enableTeamManagement, _settingValue=0 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_interaction_enableTeamManagement] type not valid [0] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Launchers, _settingName=ace_missileguidance_enabled, _settingValue=2 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_missileguidance_enabled] type not valid [2] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Hide AI groups on map?, _settingName=ace_map_BFT_HideAiGroups, _settingValue=1 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_map_BFT_HideAiGroups] type not valid [1] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Show player names map?, _settingName=ace_map_BFT_ShowPlayerNames, _settingValue=1 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_map_BFT_ShowPlayerNames] type not valid [1] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Map default channel, _settingName=ace_map_defaultChannel, _settingValue=5 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_map_defaultChannel] type not valid [5] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Locations boost medical training?, _settingName=ace_medical_increaseTrainingInLocations, _settingValue=1 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_medical_increaseTrainingInLocations] type not valid [1] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Medical, enable revive?, _settingName=ace_medical_enableRevive, _settingValue=2 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_medical_enableRevive] type not valid [2] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Max revive time?, _settingName=ace_medical_maxReviveTime, _settingValue=300 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_medical_maxReviveTime] type not valid [300] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Medical, clean up litter delay?, _settingName=ace_medical_litterCleanUpDelay, _settingValue=600 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_medical_litterCleanUpDelay] type not valid [600] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Full heal on epi injection restricted to medic?, _settingName=ace_medical_medicSetting_basicEpi, _settingValue=0 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_medical_medicSetting_basicEpi] type not valid [0] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: MicroDAGR map fill, _settingName=ace_microdagr_mapDataAvailable, _settingValue=1 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_microdagr_mapDataAvailable] type not valid [1] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: How much damage can an engineer repair?, _settingName=ace_repair_repairDamageThreshold_engineer, _settingValue=1 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_repair_repairDamageThreshold_engineer] type not valid [1] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Full repair locations?, _settingName=ace_repair_fullRepairLocation, _settingValue=3 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_repair_fullRepairLocation] type not valid [3] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Who can perform a full repair?, _settingName=ace_repair_engineerSetting_fullRepair, _settingValue=1 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_repair_engineerSetting_fullRepair] type not valid [1] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Advanced Fatigue, _settingName=ace_advanced_fatigue_enabled, _settingValue=0 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_advanced_fatigue_enabled] type not valid [0] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Advanced Fatigue performance factor, _settingName=ace_advanced_fatigue_performanceFactor, _settingValue=2 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_advanced_fatigue_performanceFactor] type not valid [2] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Advanced Fatigue recovery factor, _settingName=ace_advanced_fatigue_recoveryFactor, _settingValue=2 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_advanced_fatigue_recoveryFactor] type not valid [2] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Advanced Fatigue terrain gradient factor, _settingName=ace_advanced_fatigue_terrainGradientFactor, _settingValue=1 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_advanced_fatigue_terrainGradientFactor] type not valid [1] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Explosives explode on defusal?, _settingName=ace_explosives_explodeOnDefuse, _settingValue=0 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_explosives_explodeOnDefuse] type not valid [0] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Advanced ballistics?, _settingName=ace_advanced_ballistics_enabled, _settingValue=1 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_advanced_ballistics_enabled] type not valid [1] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Disable Advanced Ballistics in full auto?, _settingName=ace_advanced_ballistics_disabledInFullAutoMode, _settingValue=1 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) ERROR: readSettingsFromParamsArray - param [ace_advanced_ballistics_disabledInFullAutoMode] is not an ace_setting z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:36
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Advanced ballistics simulation radius, _settingName=ace_advanced_ballistics_simulationRadius, _settingValue=1500 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) ERROR: readSettingsFromParamsArray - param [ace_advanced_ballistics_simulationRadius] is not an ace_setting z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:36
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Map Illumination, _settingName=ace_map_mapIllumination, _settingValue=1 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_map_mapIllumination] type not valid [1] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:31 [ACE] (common) TRACE: 113837 ace_setting: _title=ACE: Wheel repair requires toolkit, _settingName=ace_repair_wheelRepairRequiredItems, _settingValue=1 z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:32
 7:23:31 [ACE] (common) WARNING: readSettingsFromParamsArray - param [ace_repair_wheelRepairRequiredItems] type not valid [1] - expected type [any] z\ace\addons\common\functions\fnc_readSettingsFromParamsArray.sqf:52
 7:23:32 [ACE] (common) INFO: Settings initialized.
 7:23:32 [ACE] (common) INFO: 7 delayed functions running.
 7:23:32 "kO_epi/BIS_fnc_log: [postInit] CBA_fnc_postInit (2451.17 ms)"
 7:23:32 "kO_epi/BIS_fnc_log: [postInit] TFAR_fnc_TaskForceArrowheadRadioInit (0.976563 ms)"`

is not an ACE issue?

**Comment by Sparker95** [comment]
Can you show me the RPT? I see no way how the program can false-detect ACE presense. Nor i can see an exact match for "ACE detected" in our code. Maybe something else has falsely detected ACE?
As for the troubles with ACE logs, it looks like we've solved them by removing ACE settings from the mission. Try the new version, please.

**Comment by kOepi123** [comment]
@Sparker95 
you could test the missions that I uploaded with without ace and with RHS and CBA.
This is what was shown for me a 100 times and even when I set up a friends dedicated server with the same content and mission:

[arma3_x64_2017-12-22_11-36-20.zip](https://github.com/A3Antistasi/antistasiofficial/files/1588075/arma3_x64_2017-12-22_11-36-20.zip)

**Comment by IrLED** [comment]
@kOepi123 
Logging in the function is indeed somewhat misleading https://github.com/A3Antistasi/antistasiofficial/blob/ffdd121b0ae067dc54da1ed6c7933c2ee2e9e890/AntistasiOfficial.Altis/Functions/fn_detectACE.sqf#L29
But that **Init: ACE detection done.** only marks the end of detection script execution. no more no less.
