### ISSUE TITLE
Steam workshop release content

### ISSUE THREAD

**Issue by IrLED** [A3Antistasi/antistasiofficial#175]
https://steamcommunity.com/sharedfiles/filedetails/?id=378941393
Current Steam workshop version of Antistasi(AS) is very old. By updating it i expect better community exposure. Afaik Barbolani is in control of workshop item, and he doesn't mind to assist with updating steam version. @StefArma?

One of the requirements was to make AS vanilla friendly. Hopefully that goal should be reached by #174. Regarding the content and stability: currently VCOM is integrated to AS but disabled by default (can be easily enabled by UI or external mission properties). Some severe resource leaks of VCOM were fixed, and some tweaks to UPS were made to make those two co-exist more or less happily. Stability was the issue lately, i don't know if it was related to mission itself or related to Nitrado hardware issues.

Anyway, if it's in plans to release to Steam, let's define criteria for that.

**Comment by IrLED** [comment]
Taken from #174 
@StefArma:
About the release canditate for steam, i think we've to test the reduced delay of counterattack from same base.. i reduced it to 2 minutes instead of 20 minutes.

The point is: right now QRF are the only thing which bring action and force player to move away:
- mortar fire, killing CSAT, supply mission, DES_ mission types, conquer: they are all triggering QRF and i don't see the point to miss the reaction against mortar just because base is busy. 

Also, capture and loose of a territory multiple times has to have a cooldown on the triggered effects... otherwise too many qrf spawns (and this is happening already)

**Comment by StefArma** [comment]
Maybe a strong test in SP is required too... most of Steam users play SP considering +2000 subscribe each month since 1 years (since i'm tracking statistics) and we have 7000 users only on community website

**Comment by StefArma** [comment]
Also, the main broken features: 
- CSAT punishment (never succede, jet fly up in the sky infinitley), i'm ok to just reworking it completly to something easy like a bombardment with careless jet (like NATO carpet bombing)
- NATO aircraft don't spawn enemies so they can fly over the island without problems (we don't want them to spawn enemies infact, however we need to create some danger).

**Comment by zverofaust** [comment]
Honestly I miss the days when even killing a two-man patrol in a town would prompt a QRF sometimes. Though maybe it would be better to be an MRAP patrol rather than an APC. :)

**Comment by colmaniac** [comment]
@StefArma, I am using single player not MP, so steam version that is 1.7 atm manual save is working for me and a few others.  I dont like the 1.7.18G version with persistent save,  takes ages to reload the game, rebuy troops and rekit them out again. Give us the option to save game for SP, or tell us how we can turn it back on. save is available in 1.7 though turned off in 1.7.18G must be a code line in the file to do it.

**Comment by Sparker95** [comment]
I think that Barbolani, the initial author of Antistasi, said that arma's default save is not supported. So many times the reason when stuff got broke was that people were using the default save button.

**Comment by colmaniac** [comment]
@Sparker95, what stuff got broke Barbolani`s steam version?  I didnt have any issues, though I dont know if I had with out info of the exact problem with it lol

**Comment by Sparker95** [comment]
I just remember that he said that the default save button was always breaking something, that's why it's disabled. Maybe you simply didn't know that you had issues?
If you want  it back so much, i think the solution for you is here:
https://github.com/A3Antistasi/antistasiofficial/blob/7ab549adf2e64136cc94df83c1e27c16b2ffff0c/AntistasiOfficial.Altis/init.sqf#L3

**Comment by colmaniac** [comment]
ok, so just change both false to true?

I didnt see any errors or issues while playing, the only major one I had was using the persistent save,  after loading the persistent save it made trying to do a manual save crash.  So I avoided using that and just manual save, no errors.  Though there could be a problem`s I dont know about, as not familiar with early version of the game,  only got arma3 and mod 2 1/2 weeks ago :)

**Comment by StefArma** [comment]
We can close this for now... but indeed whenever will be possible we should consider Steam
