### ISSUE TITLE
VCOM AI Squads immediately got into statics at HQ

### ISSUE THREAD

**Issue by zverofaust** [A3Antistasi/antistasiofficial#178]
As the title says, I recruited an AI squad at my HQ and it immediately got into all the statics I had deployed at my HQ. This apparently prevented me from being able to buy a vehicle for them - it withdrew the $200 but no truck spawned. I then bought a truck to manually add vehicle to squad but it wouldn't work because squad members were in statics. However, half the squad actually got into the truck anyway without it being assigned, and started driving away randomly.

VCOM :(

**Comment by StefArma** [comment]
Is this fixed now?

**Comment by IrLED** [comment]
>Is this fixed now?

No
VCOM is disabled by default (server owner still can enable it by param). Only obvious resource leaks were corrected, which still keeps VCOM vanilla. All further VCOM activities are on hold. Maybe VCOM was the wrong detour.

**Comment by StefArma** [comment]
ok!

**Comment by ElectroEsper** [comment]
What if statics are locked by default to AIs? Is there no way to deactivate that part of VCOM (static occupation)?

**Comment by StefArma** [comment]
VCOM won't be supported
