### ISSUE TITLE
Remove Default Gears

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#18]
It's annoying that new connected players have vanilla gears when there are mods enabled, so i want to remove all the gears.

I tried with a script but it ended up removing gears periodically even to players
Now i'm trying by editing loadout in .sqm let's see

Default Gears are applied when = random civ uniform from avail list, bino, map, radio, compass, watch, earplugs if ACE
**Acceptance criteria:**
Default Gears - random civ uniform from avail list, bino, map, radio, compass, watch, earplugs if ACE
Default gears applied:
- SP Start New Campaign  :white_check_mark:
- MP Joining server for first Time  :white_check_mark:

Default gears **not** applied (loadout restored from previous save event)
- SP Load Persistent Save  :white_check_mark:
- MP New campaign  :white_check_mark:
- MP Joining a server you were already  :white_check_mark:

**Comment by StefArma** [comment]
In current version it looks working with edited loadout from the .sqm  the file size increased by 10 kb, and i think it's fine... if any bug related to, please notice it here

**Comment by StefArma** [comment]
In Singleplayer

- spawn ok
- persistent save
- persistent load 
- spawn with vanilla gears

**Comment by IrLED** [comment]
Some useful info found regarding default starting gear
http://killzonekid.com/arma-scripting-tutorials-basic-multiplayer-coding-v2/

**Comment by StefArma** [comment]
Thanks!
Default gears looks ok now.

the only issue is in the SP persistent save without inidibi2, after load it give me vanilla geras.

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/commit/2ad1d76b0b1320cb55110c1d6f71563cb65505ce this fixed, thanks IrLED

**Comment by StefArma** [comment]
Not happening when CBA only

Probably something about RHS or ACE, have to investigate further

**Comment by IrLED** [comment]
Looks like the case i forgot to cover, when it's the fresh start and there is no load-out saved

**Comment by StefArma** [comment]
Tested singleplayer
Start new game
I spawn with typical guerrilla gears

(in the .sqm there is still the model without gears)

**Comment by IrLED** [comment]
Somewhere i read that loadout-money-rank is kept from campaign to campaign

Test scenario:
- shut down Arma3 (if started).
- remove (with backup) vars.Arma3Profile or iniDB2 (depends what is in use).
- Start Arma3
- Start new campaign
- Check loadout
- :white_check_mark: Check RPT for entries `[ANTISTASI] (Save) TRACE: 25193 fn_loadPlayerData: value loaded:  _varName=loadout,  _varValue=<NULL-object>` -> (**\<NULL-object\>** = no loadout was previously saved, even in the other campaign)
- :no_entry_sign: if ` _varValue=[some array data]` -> previous save loadout was loaded

I PASSED the test scenario :white_check_mark:

**Comment by IrLED** [comment]
>without inidibi2

There might still be the info in  `vars.Arma3Profile`

**Comment by StefArma** [comment]
So you're saying this update is incompatible with previous saves? i'll try to remove my vars.Arma3profile

**Comment by StefArma** [comment]
It works

**Comment by IrLED** [comment]
>So you're saying this update is incompatible with previous saves?
Never said that. Game won't give default gear if you have loadout already saved.
AS has two saving mechanisms - profileNameSpace and iniDB2. profileNameSpace is always available (Arma3 native), inidb2 is preferable if active.

**Comment by StefArma** [comment]
Ok, another test, if i save and then i try to start a new game i keep having the gears. It's ok-ish in MP maybe not in SP infact

**Comment by IrLED** [comment]
I edited first post, added **Acceptance criteria**
>It's ok-ish in MP maybe not in SP infact

please define another acceptance item
