### ISSUE TITLE
Zeus usage sometime doubles all garrisons

### ISSUE THREAD

**Issue by zverofaust** [A3Antistasi/antistasiofficial#181]
I know Zeus usage has been officially dropped from Antistasi but I thought I'd report this anyway in case it's a bigger issue that Zeus is just triggering.

Basically, if you're close enough to a friendly garrisoned zone and enter and exit Zeus it will often double the garrison, ie spawn the garrison again and again every time you enter Zeus. Found this out after I was using Zeus to make my HQ look super pretty and ended up inadvertantly spawning 100+ FIA troops at a nearby powerplant.

All statics assigned to the base will also get doubled, so there was a pile of 20 Dshkms on the ground around where I had just one. This didn't happen with the statics at my own HQ nor recruited FIA Squads, it's limited to garrisons.

**Comment by StefArma** [comment]
Zeus is not supported anyway, there are other issues dealing with garrison duplication already
