### ISSUE TITLE
FIA Squads no longer refunded after save/load

### ISSUE THREAD

**Issue by zverofaust** [A3Antistasi/antistasiofficial#182]
I remember back in the day you used to get refunded for FIA squads you recruited when you saved/loaded, but this no longer happens - the squads are gone upon loading and the HR and money don't get refunded.

EDIT: Also last time I checked, dismissing a recruited squad will also not refund you anything.

**Comment by StefArma** [comment]
Tested right now, in singleplayer it's not refunding nor HC squad nor recruited units.
I used default save system.

**Comment by StefArma** [comment]
Fixed HR refund
https://github.com/A3Antistasi/antistasiofficial/pull/219/commits/a5ad9648d14dd60b12a74c6608333d1adb80db6a

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/pull/219
