### ISSUE TITLE
Vehicles sink under the ground-aaf planes crash the server.

### ISSUE THREAD

**Issue by kapania** [A3Antistasi/antistasiofficial#183]
We're using a dedicated server from gameservers.com with the mods ARAF, GREF, USMC, advanced towing and advanced sling loading.
tried 1.7.18 and 1.7.18G
All the latest versions from armaholic.

We have a problem with cars/trucks, GAZ cars: Most times when the enemy disembarks a GAZ car it sink under the ground with only the roof sticking up, the few times it stays above ground or when we go for a Kill the traitor mission the GAZ is above the ground until a player enters it, then it is instantly teleported under ground, when we exit it comes back up and starts to flip and always land upside down.

The trucks would it be repair/fuel or transport got some sort of anchor at the back, when we drive forward the front end lifts up until the front is facing the skies.

AAF Attack: whenever they use planes against us on a base/outpost the game crashes with the error "bad module", same happends if we use USMC airstrikes.

**Comment by StefArma** [comment]
Couldn't reproduce
