### ISSUE TITLE
increase hr/army xp

### ISSUE THREAD

**Issue by kapania** [A3Antistasi/antistasiofficial#184]
not really an issue but the forum is down so i'll try my luck here.

running a dedicated server with RHS mods but the problem is that most rhs cars/trucks won't work and the aaf planes crash the server.

is it possible to restart the server without the rhs mods and add levels/hr manualy so we don't lose 2 weeks of playing?

**Comment by Sparker95** [comment]
Make a backup of your .arma3profile and try it. You will surely lose RHS weapons and RHS vehicles. But you can sell the vehicles and get a sort of refund.

**Comment by kapania** [comment]
Thanks, that worked but then i noticed the vehicle crate was gone so we had to restart anyway:(
