### ISSUE TITLE
Dedicated Server / Mission Startup and save issues since .18

### ISSUE THREAD

**Issue by ddarz** [A3Antistasi/antistasiofficial#185]
Hi all,

I've been having issues getting Antistasi started properly since the first .18 release
The mission seems to run normally if it is started in SP, but when it is launched on a dedicated server or or as a LAN host, then the following behaviour occurs:

As soon as continue is pressed on the first briefing map, the game immediately starts, without giving the player the chance to use the pda to set up the starting parameters. Sometimes it just goes straight into HQ placement mode. No progress is saved either.

This has been tested with and without mods (apart from the required CBA). I've also tried with and without VCOM enabled, and added as a mod.

Any ideas or advice? I cant see anything standing out in the logs and the behaviour is consistent.

Cheers

**Comment by StefArma** [comment]
Hello, my bad i haven't added this to the wiki... nor to release note

https://github.com/A3Antistasi/antistasiofficial/wiki/Dedicated-server-setup#multiplayer-notes

**Comment by ddarz** [comment]
Hi, thanks for the reply @StefArma !

Sadly it wasn't the parameters, I've been using the "Start fresh campaign..." parameter for a while - i think it was added a few versions ago no? Sorry I should have mentioned that I tested various parameter combinations.

I just tried again, and its the same behaviour, even with the new campaign parameter on, the mission just starts straight into the mission, with the base in the default position and the player about 100 meters north. Sometimes it moves the player to the base after a few seconds. No PDA unless I call it up :(

I think something in the mission script is failing to launch or initialise properly, but I can't think what it might be...
By the way is VCOM required as an addon, or is it baked into the mission pbo? Would the server RPT help?

**Comment by StefArma** [comment]
Pretty strange...
what do you mean for a while? it's a single time usage: when you wanna select HQ then you change parameter and when mission start it ask commander to place HQ.

Are you using inidibi2 as server mod or not?

VCOM is inside the mission, noone has to download anything extra

**Comment by ddarz** [comment]
Sorry, by "a while" i meant I was aware of the parameter's existence since it was introduced, and used it only whenever a new campaign was started

I tried to get things running with and without inidbi2 just in case it was the source of the problem. I've used it in the past with no issues.

Thanks for the clarification on VCOM :)

Aye, I'm getting quite frustrated, I've run an Antistasi server for a while and this issue is new and so far unexplainable. Could something be cached somewhere? Where are games saved on a dedicated server when inidbi2 is not used?

**Comment by StefArma** [comment]
with inidibi2 i've no problem experiences, i did less test with default save infact.

come on TS this evening (EU time) or add me on steam http://steamcommunity.com/profiles/76561198005296652/  maybe the issue is just something on procedure or maybe not

**Comment by ddarz** [comment]
Cheers :) I'll see you in TS later on

**Comment by ddarz** [comment]
Closing as the issue was partially solved. Opening new ticket for new specific issue.
