### ISSUE TITLE
persistent save not working properly, bring back standard save

### ISSUE THREAD

**Issue by colmaniac** [A3Antistasi/antistasiofficial#187]
As above, persistent save causing me issues, spawning miles from HQ squad missing having to keep rebuying and kitting out.  Bring back option to save game any time, I had no problems with that.

**Comment by StefArma** [comment]
Join Teamspeak for instruction, you're doing something wrong.

**Comment by colmaniac** [comment]
I am using single player not MP, so steam version that is 1.7 atm manual save is working for me and a few others.  I dont like the 1.7.18G version with persistent save,  takes ages to reload the game, rebuy troops and rekit them out again. Give us the option to save game for SP, or tell us how we can turn it back on. save is available in 1.7 though turned off in 1.7.18G must be a code line in the file to do it.

**Comment by StefArma** [comment]
- i explained in TS for 5 minutes that vanilla save break the mission
- i linked you the guide and then you couldn't understand it (regardless your flag indicate UK...
- you can keep playing your broken mission, if you don't like this one no need to keep asking your stuf in multiple posts.

Once and for all: Every units who are loaded by vanilla save won't follow spawn/despawn rules so you're duplicating and creating units without any control from the mission script. Enough?
Save was available there for a mistake that caused a lot of people asking why their mission was broken.
