### ISSUE TITLE
Loading mods on server/ memberlist issues

### ISSUE THREAD

**Issue by EXpaens** [A3Antistasi/antistasiofficial#189]
Hello all.

In last days we were started our own server and we have problem with loading mod to game.
After consulting with Stef, we had to placed from all mod what we want, "key" file to folder in Arma 3 folder. This way we activate mod in game. Stef ask me to write this here, because of guide.

Our next issue is with memberlist on server. All time we get message that memberlist is disabled and anybody who connect on server can be Commander. :(.

Thank you all

**Comment by StefArma** [comment]
Hi! 

Create this file on server
\Arma3\A3Antistasi\memberlist.txt

edit it and add user ids warping one by one so 

76561198005296652
76561198005296652
76561198005296652

Membership can be disabled by Parameters when starting the game, be sure you leave it default (enabled)

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/wiki/Dedicated-server-setup 

thanks! added here, 

close the issue if that fix it
