### ISSUE TITLE
Outpost cache box and truck`s bug? May been reported b4

### ISSUE THREAD

**Issue by colmaniac** [A3Antistasi/antistasiofficial#190]
Over the last 10 min`s I have been raiding an outpost, no killing, just grab and run.
I loaded the truck with the crate, returned to HQ unloaded the crate and sold the truck, I then returned back to the Op and a truck & crate had respawned while I was away, done this 3 times now.  Is this a bug?  As seems easy way to get gear.

**Comment by StefArma** [comment]
No that's actually good way to scavenge... Antistasi is about hit&run :) gg!
