### ISSUE TITLE
persistent save, got money back but not hr

### ISSUE THREAD

**Issue by colmaniac** [A3Antistasi/antistasiofficial#191]
as to manual says on a reload, I should have got my HR back I spent on my unit soldiers but 0HR points from 9 soldiers.

**Comment by StefArma** [comment]
Require tests, i heard of it before

**Comment by colmaniac** [comment]
ok, I got about 2k in cash back though.

**Comment by StefArma** [comment]
change the 0 with the value you prefer, put that into the console and local exec

server setVariable ["HR",0,true];

**Comment by colmaniac** [comment]
ok ty, il have a look to see where to put it, not much of a programmer lol

**Comment by colmaniac** [comment]
another bug, after reload all except helmets are returned,

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/pull/219/commits/a5ad9648d14dd60b12a74c6608333d1adb80db6a  

sorry for the long delay... this change is still on my develop branch, when all will be completed i'll merge in master version
