### ISSUE TITLE
Mission fails to initialise or assign a commander

### ISSUE THREAD

**Issue by ddarz** [A3Antistasi/antistasiofficial#192]
Narrowed the problem down to a reproducible issue with the latest versions:

Currently as soon as the mission begins the HQ is created at the default location and the player is position about 100 meters north of it (also a default location). The player is never teleported to the HQ and importantly the info bar never appears. 

This happens regardless of any combination of parameter settings

Did this happen on the Official Server too? Let me know if I can provide any further details

Cheers

**Comment by IrLED** [comment]
@ddarz, it's rather specific but known issue.
It also happens from time to time on official (when mission restarts but there is no commander at the moment of restart)

**Comment by StefArma** [comment]
If you could attatch an .rpt that would help...

as IrLED said, sometime happen on official server that player isn't teleported to the new HQ location and see a specular copy of it at the initial position (however it despawn once the player fastraveled)

**Comment by ddarz** [comment]
Hi @StefArma , sorry for the delay, got some RPTs for you
These one's have some mods enabled (nothing too crazy, just ACE and RHS mostly), but the same behaviour occurs with CBA-only setups

[Antistasi_1.zip](https://github.com/A3Antistasi/antistasiofficial/files/1607932/Antistasi_1.zip)

**Comment by StefArma** [comment]
First .rpt
Antistasi never loaded.

-----

Second .rpt
22:35:52 Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.

Antistasi never loaded

-----

"[KP LIBERATION] [CHECKCLASS] LOP_ISTS_OPF_Truck not found in CfgVehicles"
"[KP LIBERATION] [CHECKCLASS] BW_AW101_Trans_Heer_F not found in CfgVehicles"
"[KP LIBERATION] [CHECKCLASS] UK3CB_BAF_Merlin_HC3_18_DPMT not found in CfgVehicles"
"[KP LIBERATION] [CHECKCLASS] UK3CB_BAF_Merlin_HC3_32_MTP not found in CfgVehicles"


[ACE] (common) INFO: Extension version: ace_clipboard: 3.8.4-ef4d289
CallExtension loaded: ace_fcs (M:\Steam_M2_960\steamapps\common\Arma 3\!Workshop\@ace\ace_fcs_x64.dll) [
Pî]

wondering why those appear.. it looks like the last .rpt is about liberation, not antistasi.


Can i see an .rpt with CBA only?

**Comment by ddarz** [comment]
Doh! Sorry my bad, TADST puts rpt's in different folders depending on profiles :/
Here is a clean one with CBA only (and inidbi2)
[arma3server_x64_2018-01-06_11-03-53.zip](https://github.com/A3Antistasi/antistasiofficial/files/1608720/arma3server_x64_2018-01-06_11-03-53.zip)
