### ISSUE TITLE
"Y" key console ui bug

### ISSUE THREAD

**Issue by colmaniac** [A3Antistasi/antistasiofficial#195]
got an annoying bug with the ui interface,  happens all the time.  I can open the interface but cannot select any options on the unit, fast travel, ai settings, game settings etc.  To get access I have to press the esc key several times before the UI is accessible.  This part is random ;-  on a reload and during the game I can press the esc key anywhere between 2 to 25 times before it unlocks before I can use it.  Every game is the same with ever I use it, the most common is 20 times each time I want to use it.  some games, not many up to 3.  To rearm say 9 soldiers I have to press the esc key 180 times for all of them lol, (20 for each one).

**Comment by StefArma** [comment]
You're doing something wrong, this is not happening on our end.

**Comment by colmaniac** [comment]
I have some more info while testing over the last week or so.  Loading a game from a fresh startup of arma3 the console works with just 1 click on any option.  Reloading game again without restarting a3 then seems I have to press the escape key twice to "unlock" the console as it seems to be locked out.  Tried Reloading several times seems that I have to press the escape key same amount of times as I reloaded.  The only fix is to quit a3 and restart a3.  I'll see if I can get a video of what's happening.  I can't see what I'm doing wrong.  Case of pressing y and selecting the option  I want.

**Comment by gallexme** [comment]
@StefArma  its a common error that the Y Menu Bugs out, dont close this Issue

**Comment by StefArma** [comment]
Never happened on official server.. i can reproduce it only when i do a restart in singleplayer

**Comment by colmaniac** [comment]
@gallexme, thanks for support and not just me with bug :)
