### ISSUE TITLE
No entry 'bin\config.bin/CfgMagazines.'

### ISSUE THREAD

**Issue by fuchstraumer** [A3Antistasi/antistasiofficial#197]
When loading a previous save, the error message shown above appears.

Log output contains more info:
```
18:56:37 [ANTISTASI] (Save) LOG: fn_loadData: Success: variable magazines: [""] missions\__cur_sp.altis\Save\fn_saveFunctions.sqf:148
18:56:37 Warning Message: No entry 'bin\config.bin/CfgMagazines.'.
18:56:37 Warning Message: No entry '.picture'.
18:56:37 Warning Message: '/' is not a value
18:56:37 Warning Message: No entry '.scope'.
18:56:37 Warning Message: '/' is not a value
18:56:37 Warning Message: Error: creating magazine  with scope=private
18:56:37 Warning Message: No entry '.displayName'.
18:56:37 Warning Message: '/' is not a value
18:56:37 Warning Message: No entry '.displayNameShort'.
18:56:37 Warning Message: '/' is not a value
18:56:37 Warning Message: No entry '.nameSound'.
18:56:37 Warning Message: '/' is not a value
18:56:37 Warning Message: No entry '.Library'.
18:56:37 Warning Message: No entry '.libTextDesc'.
18:56:37 Warning Message: '/' is not a value
18:56:37 Warning Message: No entry '.type'.
18:56:37 Warning Message: '/' is not a value
18:56:37 Warning Message: No entry '.count'.
18:56:37 Warning Message: '/' is not a value
18:56:37 Warning Message: No entry '.maxLeadSpeed'.
18:56:37 Warning Message: '/' is not a value
18:56:37 Warning Message: No entry '.initSpeed'.
18:56:37 Warning Message: '/' is not a value
18:56:37 Warning Message: No entry '.reloadAction'.
18:56:37 Warning Message: '/' is not a value
18:56:37 Warning Message: No entry '.modelSpecial'.
18:56:37 Warning Message: '/' is not a value
18:56:37 Warning Message: No entry '.ammo'.
18:56:37 Warning Message: '/' is not a value
```
Unsurprisingly, my arsenal is empty of magazines. The window or icon doesn't even appear for clicking. I'm reading through fn_SaveFunctions but I don't see anything (given my relative lack of .sqf experience, and no knowledge of the codebase lol) that stands out.

I'm using only two mods - TPW Mods, and tort_DynamicWeather2 (but a version compiled entirely to PBO + fix'd up by me).

Beyond this point I'm flying on a hunch - I found out where Antistasi savedata is "vars.Arma3Profile", and used DeRap on it to get a peek at the insides. The magazines entry is empty, and looks like this:
![magazines](https://user-images.githubusercontent.com/11087615/34806950-c4b7f2e4-f63a-11e7-9760-eea607a1595a.PNG)

Other entries in that file reflect further log output from fn_SaveFunctions in my .rpt file, so I guess something isn't saving correctly? There definitely should be a number of magazines in there, and there are reasonable entries for the unlocked magazines. They don't appear even immediately after storing things in the Arsenal. This error is really a bummer, because losing all my magazines when I load them in the Arsenal really makes things harder! Right now in my latest re-load I have no ammo whatsoever lol (not even for the starting weps). Any suggestions for quick patches would be _quite_ welcome. This has happened more than once, too.

Also, I'm running the latest version compiled to a .pbo as well. I saw some recent logistics patches and hope they fixed this issue, but alas they have not. As a sidenote, this also means that about 3/4 of every reload of a save result in me not teleporting with my HQ, and sometimes I can't even fast travel without a lockup.

Edit: Also as a weird note, the arsenal still seems to think it has ammo. It gives the little descriptor using the magazine icon green/red about how much ammo each weapon has stored, but it doesn't let me access it. The only icons I see on the right are for attachments.

Edit2: Actually now my spawned squadmembers are also missing weapons + ammo D:

**Comment by StefArma** [comment]
Shit i just saw this... well it looks it isn't gamebreaking.. anyway i'll have a look!

**Comment by StefArma** [comment]
Usually i get that message when i saved a game with RHS mods and then i load the game without RHS

**Comment by Sparker95** [comment]
"magazines" are the magazines of the **inventory** of the ammo box, not the **arsenal**. All the items of the **arsenal** are saved through "jna_datalist" variable and it should contain the magazines of the **arsenal**. Are you sure you are not confusing the arsenal and the inventory?

**Comment by zalexki** [comment]
Already had this message a shit ton of times in a big milsim group caused by the change of mods.
Looks like the save file has been done with different mods/version than you're actual setup. (be aware of BC break of the saveFile in 1.8).

Feel free to re-open and give more infos about your problem.
