### ISSUE TITLE
despawn after save and reload, general bases.

### ISSUE THREAD

**Issue by colmaniac** [A3Antistasi/antistasiofficial#199]
Not sure where to put this but, need some more info.  After capturing a few bases and cp's is it safe to leave any vehicles statics at bases and cp's near their relevant flag  and they wont despawn after a save reload?
Thanks

**Comment by StefArma** [comment]
?

**Comment by colmaniac** [comment]
OK, thanks cp`s (capture points)

**Comment by StefArma** [comment]
Fixed in lastest version
