### ISSUE TITLE
Vehicle crate Heal& Repair and loss of "compromized" status

### ISSUE THREAD

**Issue by IrLED** [A3Antistasi/antistasiofficial#20]
When activating **Heal&Repair** there might be the situation that the **compromized** flag is not dropped. 
From the [healandrepair.sqf](https://github.com/StefArma/antistasiofficial/blob/master/healandrepair.sqf#L14), the effect is applied to the players within 30m radius around HQ pos (Petros - if he's alive). But Vehicle crate itself can be moved up to 50m from HQ pos. 
[moveObject.sqf](https://github.com/StefArma/antistasiofficial/blob/master/moveObject.sqf#L13).
That allows to create 20m dead zone between area of effect and trigger of effect (crate is on the very edge of the allowed movement zone).
It would be more consistent to use Vehicle crate as the center of effect and not HQ(Petros). Or to widen the effect area.

**Comment by StefArma** [comment]
As soon Jeroen Garage is completed that function should disappear apart the "Heal" which ofcourse must be unaccessible if enemies are withing 300m of HQ. 
Basically i want vehicles repaired from the garage with a certain cost.

**Comment by StefArma** [comment]
Is still relevant?
