### ISSUE TITLE
Unable to deploy tow ropes/load ammobox after be revived by a player or AI unit

### ISSUE THREAD

**Issue by chpich** [A3Antistasi/antistasiofficial#201]
"Deploy tow ropes" and "load ammobox in vehicle" are available at start but if i
get unsconsious and revived by AI or a player, the function just not appear at the back of the vehicle.

i made some tests, here the results :

after a revive -> deploy and load unavailable
after a respawn or reconnection -> deploy and load available again

any idea how to fix that? or maybe im the only one who has that issue?

**Comment by StefArma** [comment]
I've no reports on that on official server, could you tell which mods are you using?

**Comment by chpich** [comment]
vanilla version, no mods, playing SP or MP, and i got allways that issue

**Comment by StefArma** [comment]
testing SP no mods.. i'll update in 5 min

**Comment by StefArma** [comment]
i tried to 
- get killed by my friendly AI and i could still use tow rope and load crates
- [player] spawn medUnconscious which is the same but exclude the firendly fire and still i can use tow rope
- use tow rope form a vehicle, leave a vehicle untouched, and attatch another vehicle to another one. so i had 4 vehicles and after i get revived by AI i still could interact with all of them with towing system

**Comment by chpich** [comment]
I'm a bit confused, i reinstalled everything : arma3, new game profile, redownload mission file, nothing seems to fix that, i tried .pbo 1st i got that error : 
![5- trying to start with compressed mission file pbo](https://user-images.githubusercontent.com/35432509/34924619-c31ae578-f9a4-11e7-9e28-f759e43debcd.jpg)

then i used with unpacked files and i was able to launch the mission, so i started a fresh new game

1st i bought an offroad and a medic, deploy action is ok

![1 - fresh start able to deploy](https://user-images.githubusercontent.com/35432509/34924669-1603a586-f9a5-11e7-8aa2-6b9064bb1502.jpg)

then i take damage on the campire to become unconsious

![2- taking damage on campfire](https://user-images.githubusercontent.com/35432509/34924692-2eb610dc-f9a5-11e7-8e0a-5817c4ab1f76.jpg)

AI is going to revive me

![3- reviving by ai](https://user-images.githubusercontent.com/35432509/34924707-40ae728e-f9a5-11e7-9ecb-622b6ab8f208.jpg)

once healed i tried to deploy tow ropes but action is not displayed (offroad is not the same color but it is normal because i failed to take the screenshot the 1st time)

![4- deploy action disapeared](https://user-images.githubusercontent.com/35432509/34924722-568f52da-f9a5-11e7-9397-e059bf81455f.jpg)

i dont know what i'm doing wrong, i tried same protocol on SP, LAN, internet host, and on my dedicated server, same results

**Comment by StefArma** [comment]
I assume the version you're using is the current master because the lastest release still has dependency on CBA so you couldn't play it without mods

**Comment by StefArma** [comment]
i did it again on master version. Did the exact same procedure of getting killed on campfire and got revived by my medic AI and i could interact.

Crazy idea, maybe there is something wrong with the french translations, try it once in english and tell me if you've the same error but first let's be sure we're testing on the same version

**Comment by chpich** [comment]
I use master branch 1.7.18H because 1.7.18G.pbo cannot be loaded in mission selection without CBA

so i did what you said, I switched my game to english but same results
then i have installed latest CBA, same results with both version : master branch 1.7.18H and 1.7.18G.pbo

that is really weird because my friends have the same problem on their PC, we're still playing antistasi on my server because we like it but we have to debug that by respawning instead of be revived, that is a bit annoying but still playable

Thanks for your time.

**Comment by StefArma** [comment]
Ok then we used the same version.. can you attatch an .rpt of the moment after you get revived, please?

**Comment by AlexTriada** [comment]
I confirm the presence of this bug, sometimes the possibility of towing disappears

**Comment by StefArma** [comment]
Then it's lying there since ages i think... have no clue on how to fix

**Comment by AlexTriada** [comment]
Maybe you need to update the towing script?

**Comment by AlexTriada** [comment]
The problem occurs on servers without mods to me

**Comment by StefArma** [comment]
Hadn't tought about it, i'll try!

**Comment by StefArma** [comment]
Updated the script in the mission
