### ISSUE TITLE
[stringtable update bug] Empty fields in Mission Param screen in 1.7.19

### ISSUE THREAD

**Issue by Aposky** [A3Antistasi/antistasiofficial#215]
Mission version 1.7.19

Hello,

I'm getting this in Mission Parameters screen. Logged as an admin.

![20180124005405_1](https://user-images.githubusercontent.com/6876572/35326573-66daa53c-00f7-11e8-8476-297b9d8974e2.jpg)

In code, I got this:

class Params {
    class AS_enableCampaignReset {
        title = $STR_DES_ATSAFC;
            values[] = {0,1};
            texts[] = {$STR_DES_OFF,$STR_DES_ON};
            default = 0;
            typeName = "BOOL";
            force = 1;
    };
    class AS_enableSwitchComm {
        title = $STR_DES_ESWCMD;
            values[] = {0,1};
            texts[] = {$STR_DES_OFF,$STR_DES_ON};
            default = 0;
            typeName = "BOOL";
            force = 1;
    };
    class AS_enableServerMember {
        title = $STR_DES_ESRMBR;
            values[] = {0,1};
            texts[] = {$STR_DES_OFF,$STR_DES_ON};
            default = 1;
            typeName = "BOOL";
            force = 1;
    };
    class AS_param_useJNA {
        title = $STR_DES_USABJN;
            values[] = {0,1};
            texts[] = {$STR_DES_OFF,$STR_DES_ON};
            default = 1;
            typeName = "BOOL";
            force = 1;
    };
	//added by Fireman 12/08/2017
	class AS_param_tkPenalty {
        title = $STR_DES_PPFT;
            values[] = {0,1};
            texts[] = {$STR_DES_OFF,$STR_DES_ON};
            default = 0;
            typeName = "BOOL";
            force = 1;
    };
    class AS_param_onlyPermanentMembers {
        title = $STR_DES_OPMAEFCAS;
        values[] = {0,1};
        texts[] = {$STR_DES_OFF,$STR_DES_ON};
        default = 1;
    };
    class AS_enableVCOM {
        title = $STR_DES_ENVCOMAI;
        values[] = {0,1};
        texts[] = {$STR_DES_OFF,$STR_DES_ON};
        default = 0;
        typeName = "BOOL";
        force = 1;
    };

By looks of it: AS_enableSwitchComm, AS_enableServerMember, AS_enableVCOM don't have proper title.

I didn't have that in 1.7.18G

**Comment by StefArma** [comment]
Might be cause of the update of stringtable, thanks for report, just to be clear is it from the release .pbo or simply master version?

**Comment by Aposky** [comment]
Master version, however I experienced something similar with release version.

**Comment by Aposky** [comment]
https://github.com/A3Antistasi/antistasiofficial/blob/master/AntistasiOfficial.Altis/Stringtable.xml

Still has old Mission Param

**Comment by StefArma** [comment]
Yes, confirm, i see it.. also in the briefing credits aren't shown correctly

**Comment by StefArma** [comment]
Another commit, https://github.com/A3Antistasi/antistasiofficial/pull/217
i have to check if that fixes it

**Comment by StefArma** [comment]
negative, looking into it

**Comment by StefArma** [comment]
Fixed

**Comment by Aposky** [comment]
I just updated Antistasi from latest master build.
There is small error with USMC CAS Aircraft translation in PDA.

![20180128174500_1](https://user-images.githubusercontent.com/6876572/35485257-27c91c52-045d-11e8-9fff-866c813b5a57.jpg)

It's shown it in Russian.
