### ISSUE TITLE
Spawn counter

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#22]
_groupType = [infPatrol, side_green] call AS_fnc_pickGroup;
_group = [_spawnPos, side_green, _groupType] call BIS_Fnc_spawnGroup;

For each BIS_Fnc_spawnGroup i'm interested into get a count of units of the 2 item of the array.

Any idea how?
I tried unsuccesfully with 
diag_log format ["STEF Unit spawned %1",_group select 2];

I think it's very important control how many units are going to spawn in order to balance performances better in the future

**Comment by IrLED** [comment]
AFAIK
[BIS_fnc_spawnGroup](https://community.bistudio.com/wiki/BIS_fnc_spawnGroup) returns the [Group](https://community.bistudio.com/wiki/Group) object (not array).
You can use [units](https://community.bistudio.com/wiki/units) operator.
>_myUnitCount = count units group player;

In your case it could be something like
```
_groupType = [infPatrol, side_green] call AS_fnc_pickGroup;
_group = [_spawnPos, side_green, _groupType] call BIS_Fnc_spawnGroup;
_unitsArray = units _group;
_unitsCount = count _unitsArray;
```
Something like that
