### ISSUE TITLE
QRF Vehicles despawning as soon as driver die

### ISSUE THREAD

**Issue by toddhisel** [A3Antistasi/antistasiofficial#227]
( Just so people know I am playing SP and am using ACE mod.) I shot down a transport heli ( in 1.7.19 Pre-release ) it crash landed it did not blow up. It was coming to take back a outpost i just had took. The people got out but the pilot and co pilot did not, so i killed all the people that got out.  Then i could not get in because the pilots was still in it and alive, so i shot them and as soon as i did that the heli disappeared. Also has done the same things with transport trucks that are coming to take back outpost i have took. Anyone elst having any issues like that?

**Comment by Aposky** [comment]
I had similar issue. Dedicated server, ACE + RHS + RHS compat. One of the players killed enemy truck drivers and vehicle despawned.

**Comment by StefArma** [comment]
Yes that's possible, still working on a fix

**Comment by StefArma** [comment]
acutally it despawn when driver is dead. 

It's a bit of a mistery how that's happening.. i'll dig it

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/commit/ed73af7fb6b88a2461c6237739cc66ba6c352ca9 looks fixed in SP... tried on some QRF but it indeed need extensive test!

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/pull/219
