### ISSUE TITLE
.rpt 1.7.19A4

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#228]
TIME are USA timezone

17:20:29 Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.
ace_minedetector 
17:22:19 Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.
ace_refuel

17:26:39 Error in expression <};
} forEach _containers;
};

if (count _weaponsItemsCargo > 0) then {
{
_weapon>
17:26:39   Error position: <_weaponsItemsCargo > 0) then {
{
_weapon>

17:33:10 Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.
ace_refuel

17:26:39   Error Undefined variable in expression: _weaponsitemscargo
17:26:39 File Functions\fn_transferGear.sqf [AS_fnc_transferGear], line 28

17:42:16 Attempt to override final function - jn_fnc_garage
17:42:16 Attempt to override final function - jn_fnc_garage_releasevehicle
17:42:16 Attempt to override final function - jn_fnc_garage_requestvehicle

17:50:25 Road not found
17:50:26 Road not found
17:50:27 Road not found

17:50:56 Error in expression <ir _azi;
if (_precisePosition) then
{
_veh setPos _pos;
};
if (_sim == "airp>
17:50:56   Error position: <_veh setPos _pos;
};
if (_sim == "airp>
17:50:56   Error Undefined variable in expression: _veh
17:50:56 File A3\functions_f\spawning\fn_spawnVehicle.sqf [BIS_fnc_spawnVehicle], line 80
17:50:56 Error in expression <rp) then
{
_grp selectLeader (commander _veh);
};
[_veh, _crew, _grp]>
17:50:56   Error position: <_veh);
};

[_veh, _crew, _grp]>
17:50:56   Error Undefined variable in expression: _veh
17:50:56 File A3\functions_f\spawning\fn_spawnVehicle.sqf [BIS_fnc_spawnVehicle], line 97
17:50:56 Error in expression < must be a Number!"; []};
if ((typeName _type) != (typeName "")) exitWith {debug>
17:50:56   Error position: <_type) != (typeName "")) exitWith {debug>
17:50:56   Error Undefined variable in expression: _type
17:50:56 File A3\functions_f\spawning\fn_spawnVehicle.sqf [BIS_fnc_spawnVehicle], line 50
17:50:56 Error in expression <osition, _markerPos] call BIS_fnc_dirTo,_vehicleType, side_green] call bis_fnc_s>
17:50:56   Error position: <_vehicleType, side_green] call bis_fnc_s>
17:50:56   Error Undefined variable in expression: _vehicletype
17:50:56 File mpmissions\__cur_mp.Altis\CREATE\combinedCA.sqf, line 252
17:50:56 Server: Object 7:2260 not found (message Type_109)
17:50:56 Error in expression <icle;
_vehicle = _vehicleData select 0;
_vehicle setVariable ["OPFORSpawn",true]>
17:50:56   Error position: <_vehicle setVariable ["OPFORSpawn",true]>
17:50:56   Error Undefined variable in expression: _vehicle
17:50:56 File mpmissions\__cur_mp.Altis\CREATE\**combinedCA.sqf, line 254**

18:30:01 [ACE] (common) WARNING: Could not find unload pos R Alpha 2-2:1-ASL: [3399.55,13455.9,-2.3242] isTouchingGround: false Speed: -0.312904 z\ace\addons\common\functions\fnc_unloadPersonLocal.sqf:30   repeated 20 times

3:02:44 Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.
task_force_radio_items
 2:51:48 Warning Message: You cannot play/edit this mission; it is dependent on downloadable content that has been deleted.
ace_vector

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/blob/17822d06c25a07d00ffd7b7f53551a5fc40f16c3/AntistasiOfficial.Altis/CREATE/combinedCA.sqf#L252

this wasn't changed since very long... is this line broken or something?

**Comment by Sparker95** [comment]
According to Github the biggest change was 6 days ago:
https://github.com/A3Antistasi/antistasiofficial/commit/38042ed345189b5c97fc61758679df931eb1b5cb#diff-f1fa0826cf1df8609becb6b02efa788a
And some others. You can check the file history.

**Comment by StefArma** [comment]
much of indent and tabs... i haven't spotted nothing related to the error reported.. i'll try to debug that line

**Comment by StefArma** [comment]
After a server restart: 

6:20:50 Error in expression <ate [_heli, _x, 75];
_ropesObj pushBack _rope;
} forEach _ropesPos;
_heli setVa>
 6:20:50   Error position: <_rope;
} forEach _ropesPos;
_heli setVa>
 6:20:50   Error Undefined variable in expression: _rope
 6:20:50 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 211
 6:20:51 Setting invalid pitch -0.0000 for R Alpha 4-2:1 REMOTE
 6:20:52 Error in expression <ate [_heli, _x, 75];
_ropesObj pushBack _rope;
} forEach _ropesPos;
_heli setVa>
 6:20:52   Error position: <_rope;
} forEach _ropesPos;
_heli setVa>
 6:20:52   Error Undefined variable in expression: _rope
 6:20:52 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 211

Error in expression <ir _azi;


if (_precisePosition) then
{
_veh setPos _pos;
};
if (_sim == "airp>
 7:26:57   Error position: <_veh setPos _pos;
};
if (_sim == "airp>
 7:26:57   Error Undefined variable in expression: _veh
 7:26:57 File A3\functions_f\spawning\fn_spawnVehicle.sqf [BIS_fnc_spawnVehicle], line 80
 7:26:57 Error in expression <rp) then
{
_grp selectLeader (commander _veh);
};
[_veh, _crew, _grp]>
 7:26:57   Error position: <_veh);
};
[_veh, _crew, _grp]>
 7:26:57   Error Undefined variable in expression: _veh
 7:26:57 File A3\functions_f\spawning\fn_spawnVehicle.sqf [BIS_fnc_spawnVehicle], line 97
 7:26:57 Error in expression < must be a Number!"; []};
if ((typeName _type) != (typeName "")) exitWith {debug>
 7:26:57   Error position: <_type) != (typeName "")) exitWith {debug>
 7:26:57   Error Undefined variable in expression: _type
 7:26:57 File A3\functions_f\spawning\fn_spawnVehicle.sqf [BIS_fnc_spawnVehicle], line 50
 7:26:57 Error in expression <osition, _markerPos] call BIS_fnc_dirTo,_vehicleType, side_green] call bis_fnc_s>
 7:26:57   Error position: <_vehicleType, side_green] call bis_fnc_s>
 7:26:57   Error Undefined variable in expression: _vehicletype
 7:26:57 File mpmissions\__cur_mp.Altis\CREATE\patrolCA.sqf, line 207
 7:26:57 Error in expression <ck _vehicleGroup;
_allVehicles pushBack _vehicle;

if !(_vehicleType in heli_una>
 7:26:57   Error position: <_vehicle;

if !(_vehicleType in heli_una>
 7:26:57   Error Undefined variable in expression: _vehicle
 7:26:57 File mpmissions\__cur_mp.Altis\CREATE\patrolCA.sqf, line 211

**Comment by StefArma** [comment]
9:11:35 Error in expression <it select 2); alive _unit && (_altCur - _endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error position: <_endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error Undefined variable in expression: _endofrope
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 276
 9:11:35 Error in expression <tion _rope) select 0;
_unit setPosATL [(_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error position: <_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error Undefined variable in expression: _ropepos
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 270
 9:11:35 Error in expression <it select 2); alive _unit && (_altCur - _endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error position: <_endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error Undefined variable in expression: _endofrope
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 276
 9:11:35 Error in expression <tion _rope) select 0;
_unit setPosATL [(_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error position: <_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error Undefined variable in expression: _ropepos
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 270
 9:11:35 Error in expression <it select 2); alive _unit && (_altCur - _endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error position: <_endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error Undefined variable in expression: _endofrope
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 276
 9:11:35 Error in expression <tion _rope) select 0;
_unit setPosATL [(_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error position: <_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error Undefined variable in expression: _ropepos
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 270
 9:11:35 Error in expression <it select 2); alive _unit && (_altCur - _endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error position: <_endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error Undefined variable in expression: _endofrope
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 276
 9:11:35 Error in expression <tion _rope) select 0;
_unit setPosATL [(_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error position: <_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error Undefined variable in expression: _ropepos
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 270
 9:11:35 Error in expression <it select 2); alive _unit && (_altCur - _endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error position: <_endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error Undefined variable in expression: _endofrope
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 276
 9:11:35 Error in expression <tion _rope) select 0;
_unit setPosATL [(_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error position: <_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error Undefined variable in expression: _ropepos
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 270
 9:11:35 Error in expression <it select 2); alive _unit && (_altCur - _endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error position: <_endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error Undefined variable in expression: _endofrope
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 276
 9:11:35 Error in expression <tion _rope) select 0;
_unit setPosATL [(_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error position: <_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error Undefined variable in expression: _ropepos
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 270
 9:11:35 Error in expression <it select 2); alive _unit && (_altCur - _endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error position: <_endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error Undefined variable in expression: _endofrope
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 276
 9:11:35 Error in expression <tion _rope) select 0;
_unit setPosATL [(_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error position: <_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error Undefined variable in expression: _ropepos
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 270
 9:11:35 Error in expression <it select 2); alive _unit && (_altCur - _endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error position: <_endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error Undefined variable in expression: _endofrope
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 276
 9:11:35 Error in expression <tion _rope) select 0;
_unit setPosATL [(_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error position: <_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error Undefined variable in expression: _ropepos
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 270
 9:11:35 Error in expression <tion _rope) select 0;
_unit setPosATL [(_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error position: <_ropePos select 0),(_ropePos select 1),(>
 9:11:35   Error Undefined variable in expression: _ropepos
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 270
 9:11:35 Error in expression <it select 2); alive _unit && (_altCur - _endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error position: <_endOfRope) > 1} do {
if (_altPrev isEqu>
 9:11:35   Error Undefined variable in expression: _endofrope
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 276
 9:11:35 Error in expression <";
_endOfRope = ((ropeEndPosition _rope select 1) select 2);


_altPrev = 0;
whi>
 9:11:35   Error position: <select 1) select 2);


_altPrev = 0;
whi>
 9:11:35   Error Zero divisor
 9:11:35 File mpmissions\__cur_mp.Altis\Scripts\SHK_Fastrope.sqf, line 272

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/pull/219

remain the fastrope but that will be another thing
