### ISSUE TITLE
Error in translation / stringtable regarding USMC CAS

### ISSUE THREAD

**Issue by Aposky** [A3Antistasi/antistasiofficial#229]
I just updated Antistasi from latest master build.
There is small error with USMC CAS Aircraft translation in PDA.

![20180128174500_1](https://user-images.githubusercontent.com/6876572/35485257-27c91c52-045d-11e8-9fff-866c813b5a57.jpg)

It's in Russian.

**Comment by StefArma** [comment]
Thanks!

**Comment by StefArma** [comment]
fixed in next merge
