### ISSUE TITLE
Different civil's cars colors for players in MP

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/antistasiofficial#23]
For Bob the car (driving on the road by civil) is red and for Jack is not, and i am not talking about the garage.

**Comment by IrLED** [comment]
@AlexTriada 
description is not clear, please give the reproduction steps.

**Comment by AlexTriada** [comment]
What?  Do you don’t know about that? For players colors of the cars is not the same in antistasi and you don’t know about that?

**Comment by AlexTriada** [comment]
For Bob the car is red and for Jack is not

**Comment by IrLED** [comment]
@AlexTriada ok, i'll do it myself.

Reproduction steps:
color selection of the vehicle in garage is visible only to the user, performing that selection. Other players don't observe the changes (they observe the car with default color scheme)

**Comment by AlexTriada** [comment]
Fuck, how you fucked, it feels like you're an alien and you have no logic.

**Comment by AlexTriada** [comment]
I AM NOTHING SAYING ABOUT THE GARAGE!!!!

**Comment by AlexTriada** [comment]
Civil cars in the mission have different colors for the players!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by AlexTriada** [comment]
Cars on roads that drive civilians, or that are bought in the store, different players see different colors.

**Comment by AlexTriada** [comment]
In fact, it's a big problem when you tell a player, take that white car, and he's black, and that's why he does not understand you and looks at you like a fool.

**Comment by StefArma** [comment]
No solutions so far... also not that relevant compared to other issues
