### ISSUE TITLE
Captured AAF vehicles despawning during travel

### ISSUE THREAD

**Issue by michals5** [A3Antistasi/antistasiofficial#237]
I encountered this few weeks back, but action I made yesterday made me create account here and report it:).

When you take a vehicle from enemy base/outpost/QRF, it very often despawns during travel back to HQ (or any other point).

I suspect it maybe have something to do with distance you travel with them or posibly when you travel far enough so the original base despawns, vehicle you take from it despawns as well. It seems to be random fenomenom (or at least as far as I know), as some vehicle do despawn and some not. It also happened to me while flying a helicopter from base to HQ and I was ejected from it midair. 

However I also noticed, that civilian vehicles behave same way and also can randomly despawn.

**Comment by StefArma** [comment]
Yes i'm aware there is something wrong with enemy vehicle despawning... probably linked to vehicle disappearing when you kill driver of the vehicle during QRF

thanks for report!

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/commit/ed73af7fb6b88a2461c6237739cc66ba6c352ca9 let's cross fingers!

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/pull/219/commits/2f5481d29f10c2f1e60dc36ca3b449b9adab0f59 and this

**Comment by michals5** [comment]
And third video. This time we took the civilian vehicle and use it to transport to attack nearby base (with quadbike in tow). After we finished the mission, both vehicle were gone. 

Quadbike was players vehicle, truck was not, however I noticed previously, that when you garage vehicle with some other vehicle in tow, both will dissapear, while only first vehicle will be added to garage. This should probably be fixed as well tbh.

https://www.youtube.com/watch?v=9lZgkwUckkQ

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/blob/1e2fd2aea8b171c9968eb44adbed14b4e66df806/AntistasiOfficial.Altis/CREATE/VEHdespawner.sqf#L11

that's the problem maybe! i'll change the check on bluforunits around

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/pull/219/commits/d76f6534e57862efbec2f5b643767f6fd4b7e127

**Comment by michals5** [comment]
Hello Stef,

have you implement changes to solve this issue? Because BMD of QRF dissapeared twice today while I was towing them. I have a video of one if you are interested.

**Comment by StefArma** [comment]
damn...  evidently regardless my attemtps i don't test enough...

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/blob/master/AntistasiOfficial.Altis/CREATE/genVEHinit.sqf#L96

maybe something bad here

**Comment by StefArma** [comment]
Ok about towing i got why: if you don't enter the vehicle it will despawn...

**Comment by michals5** [comment]
well I entered both vehicles {driver seat}, to check at what condition vehicle actually is. 

Btw today it happened to me while in a SU-25. I tried to take off from AFRF airport to fly it back to base and it despawned 10 seconds after leaving runway.

**Comment by StefArma** [comment]
so strange i just brought back an su-25 from airport..

**Comment by StefArma** [comment]
and i went back to the airfield then back to base and it despawned.. uhmm

**Comment by StefArma** [comment]
it despawn if player go further than 1km

**Comment by Barbolani77** [comment]
then its on the garrison spawn scripts at 90% chance. You forgot to make checks of distance for BLUFORspawn on the spawned vehicles before deleting them?

**Comment by StefArma** [comment]
So, if i start it in editor and i take a jet from an airport and fly away it won't despawn.
If i port again to the place and port back where i left the plane, it disappear

**Comment by michals5** [comment]
Probably not very important info for you, but from my experience all vehicle despawns after players/friendly-AI leave the area of its existence (no matter where there are). Only exceptions are vehicles of players that remains in the area even if wrecked (including enemy bases, where somtimes you can see player vehicle from earlier, while normal enemy AI garrison is spawned around it).

**Comment by StefArma** [comment]
It's important! thanks

**Comment by StefArma** [comment]
Todays test:
1a) spawn airport, took a jet, flew away OK
1b) i disemkarked the jet at HQ and sent AI to airport OK
1c) AI left the airport OK
1d) i teleported 1km away while the AI was by my side OK
1e) teleported away the AI  !DESPAWN

2a) spawn airport, ported AI closeby airport OK
2b) took a jet and teleported to HQ (and disembarked) OK
2c) i teleported away from the jet and the AI still at the airport, the  OK
2d) i teleported the AI away from airport = DESPAWN

Conclusion: the vehicles are still bound to the airport and the function that despawn them is this: 
[_allGroups, _allSoldiers, _allVehicles] spawn AS_fnc_despawnUnits;

**Comment by StefArma** [comment]
3a) took a jet, landed in the nowhere,
3b) walked away untill i reached the distanciaspwn = DESPAWN 
so again a proof that [_allGroups, _allSoldiers, _allVehicles] spawn AS_fnc_despawnUnits; kicks in.

The point is... i can't manage to make a vehicle despawn if any "bluforspawn" units (player, FIA AI etc.) are around it

**Comment by StefArma** [comment]
And it's behaving the same in WotP

**Comment by Barbolani77** [comment]
Have you checked you have the BLUFORSpawn or whatever spawn variable in the player?

**Comment by StefArma** [comment]
Looks not happening anymore
