### ISSUE TITLE
[testbranch] Bases not spawning properly

### ISSUE THREAD

**Issue by michals5** [A3Antistasi/antistasiofficial#238]
Sometimes when you aproach the base it does not spawns as it should. There are no enemy soldiers, vehicles or static MGs on towers. Only thing that do spawns are mortars (without crew) and ammoboxes, that has vanila content (F2000, NLAW, Stoner LMG, etc).

Today we have actualy encountered this bugged base, with 6 ammoboxes (all with same content) and 6 mortars near the flag. Altough there was no enemy present (fast travel was possible), base could not be taken without taking the flag manually and even then there was no fuction like Recruit AI or Buy vehicle available at base flag.

**Comment by StefArma** [comment]
Hi michals5, which version are you playing? and which modset?

i'm almost done with my develp "territoryadjustment" and i tested hundreds of spawning and they all work

**Comment by michals5** [comment]
I am playing on official USA server.

**Comment by StefArma** [comment]
Argh! allright i'll check

**Comment by StefArma** [comment]
Let's see if this does the job https://github.com/A3Antistasi/antistasiofficial/pull/219/commits/218137a781b43c73a5afeb0d87c0ac5e656d4cce  inside here https://github.com/A3Antistasi/antistasiofficial/pull/219

**Comment by StefArma** [comment]
Should be done by now

**Comment by michals5** [comment]
Nope. Encountered same bug today twice. 

And since they say, that picture is worth thousand words, I say that video is worth long written report. I manage to capture what this bug is really about. Quality is a bit low, since a forgot to check bitrate, but I am sure you will see what I am talking about.

https://youtu.be/ilukFt_7u30?t=8

**Comment by StefArma** [comment]
ouch!

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/pull/219/commits/741fab4d5e588ed02b96a0eeac9fc49920ec0e06 Really done now ;)
