### ISSUE TITLE
Push permissions

### ISSUE THREAD

**Issue by desert5** [A3Antistasi/antistasiofficial#241]
Hello team!
I might be able to help you here and there, but regular users lack even ability to push branches and therefore create pull requests (at least this is what github client told me).
How can I get to push my local changes to pull request?

**Comment by StefArma** [comment]
Hi! People are sometime opening pull request, it should let you too ;)

By the way thanks a lot! any help is really appreciated! 


- https://github.com/A3Antistasi/antistasiofficial/wiki/Useful-scripts-for-debug-console#fork-destination-box
- Download the files
- Edit

Then

- https://github.com/A3Antistasi/antistasiofficial/compare
- click on "
compare across forks".
- select on the right your "fork" (the name you gave it)

You'll see the differences to do the last check then
- Pull Request (green button)

Done :)

**Comment by StefArma** [comment]
Consider i'm working on TerritoryAdjustment branch right now, there is a hell of changes, i'd suggest you to start from that one. Let's have a talk tomorrow on Teamspeak too, actually i might not recognise your nickname

**Comment by desert5** [comment]
Thank you for help!
