### ISSUE TITLE
Content of ACE cargo hold gone after fast travel

### ISSUE THREAD

**Issue by michals5** [A3Antistasi/antistasiofficial#245]
Since I left recording on after capture of base spawn bug, I also managed to record another irritating bug, where if you load static weapons or crater to vehicle with ACE, they will dissapear after fast travel. 

https://www.youtube.com/watch?v=UJuiFtsvOko 

Notice that after fast travel it says, that cargo capacity is 3, while only spare wheel is loaded. Normal capacity of truck is 8, so game probably knows, that something was loaded to the truck, however it canot be unloaded.

There are two fields without text in cargo menu (i didnt add this part to video, I can send you this if you want), that are obviously those two loaded things , but after I select to unload them, nothing will apear and cargo capacity will be lowered by 1.

**Comment by StefArma** [comment]
I tried to fastravel several times, no cargo was lost... infact fasttravel is nothing but a teleport with some conditions and delay.

i need to try with hilltop assets, maybe that's the problem

**Comment by michals5** [comment]
I must admit, that I have not encountered this problem since I recorded this video.

**Comment by StefArma** [comment]
Shall i close it?

**Comment by michals5** [comment]
I think so. If I encouter it egain, I will let you know.
