### ISSUE TITLE
1.7.19B3 .rpt

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#247]
SPAM
19:07:32 File mpmissions\__cur_mp.Altis\Scripts\UPSMON\MODULES\ORDERS\UPSMON_PATROL\fnc\UPSMON_SrchPtrlPos.sqf, line 84
19:07:32 Error in expression <ds = _centerpos nearRoads _rangeX;
If !(nearRoads isEqualTo []) then
{
_nearRoad>
19:07:32   Error position: <nearRoads isEqualTo []) then
{
_nearRoad>
19:07:32   Error Undefined variable in expression: nearroads
19:07:32 File mpmissions\__cur_mp.Altis\Scripts\UPSMON\MODULES\ORDERS\UPSMON_PATROL\fnc\UPSMON_SrchPtrlPos.sqf, line 84
19:07:32 Error in expression <ds = _centerpos nearRoads _rangeX;
If !(nearRoads isEqualTo []) then
{
_nearRoad>
19:07:32   Error position: <nearRoads isEqualTo []) then
{
_nearRoad>
19:07:32   Error Undefined variable in expression: nearroads

**Comment by Sparker95** [comment]
It was an obvious typo in UPS. Should be corrected in https://github.com/A3Antistasi/antistasiofficial/commit/d8dd9f40876988e0d4e010acb886b075c69c091e
