### ISSUE TITLE
1.7.19 rpt log spam

### ISSUE THREAD

**Issue by Tappczan** [A3Antistasi/antistasiofficial#248]
Hello, my RPT log is flooded with this error, any idea what's the cause or how to fix it? Version 1.7.19 from main repository.

> {
> private _marker = _x;
> private _markerPos = getMarkerPos _m>
> 12:28:11   Error position: <_x;
> private _markerPos = getMarkerPos _m>
> 12:28:11   Error Undefined variable in expression: _x
> 12:28:11 File mpmissions\__cur_mp.Altis\distancias3.sqf, line 41
> 12:28:11 Error in expression < forEach allUnits;

**Comment by StefArma** [comment]
yes main repository is obsolete check here https://github.com/A3Antistasi/antistasiofficial/pull/219

soon the merge and steam release

**Comment by Tappczan** [comment]
Downloaded the latest repository 1.7.19B3, but my RPT log still gets flooded with that error.

**Comment by StefArma** [comment]
Saves before than 1.7.17H.rc5 aren't compatible

**Comment by Tappczan** [comment]
The game was started on 1.7.19 version, the latest release version.

**Comment by StefArma** [comment]
strange i don't have it... i try to dig more... could you try with a new game? 

to keep your previous save, just backup yourprofile.vars in \documents\arma3\

**Comment by Tappczan** [comment]
Restarted the campaign, no errors shows in the RPT log now. How do I wipe my players stats to start as a Private?

**Comment by StefArma** [comment]
oh.. infact we never tought about it. With inidbi2 it's easy, just delete a file... gonna be more difficult without the mod...

**Comment by Tappczan** [comment]
That's not good, because I'm now stuck at Private rank and cannot gain any higher rank now, on disconnect RPT log shows this:

> 19:53:02 [ANTISTASI] (Save) TRACE: 744534 START fn_savePlayerData:  _varName=rank,  _varValue=,  _uid=76561198000316484 mpmissions\__cur_mp.Altis\Save\fn_saveFunctions.sqf:50

The varValue is now empty, is there a way I can manualy inject the rank with a script ingame (in admin mode)?

**Comment by StefArma** [comment]
player setrank "private"

**Comment by StefArma** [comment]
Any news?

**Comment by Tappczan** [comment]
As for now the ranks are working again and no signs of the error spam in the RPT.

**Comment by StefArma** [comment]
Nice!
