### ISSUE TITLE
Grenades no longer work

### ISSUE THREAD

**Issue by Chiisato** [A3Antistasi/antistasiofficial#252]
Tried throwing grenades on the official server and on local MP server, grenades are not being able to be thrown. 

You do the throw animation and it removes the grenade from your inventory but it does not actually throw anything and there's no explosion or smoke, same for flashbang or any other nades.

Only happens on this mission and it happens if you play vanilla

**Comment by StefArma** [comment]
did you try throw them around HQ?

**Comment by StefArma** [comment]
in that case ofcourse you can't. working fine for me everywhere else

**Comment by Chiisato** [comment]
Whelp, that explains it then. I did not know about the spawn protection. Is
it possible to turn this off? Either for everyone or trusted server members

Den 6 feb. 2018 10:53 fm skrev "Stef" <notifications@github.com>:

**Comment by StefArma** [comment]
yes it is
