### ISSUE TITLE
Location doublespawning of local "equipment"

### ISSUE THREAD

**Issue by CurePindal** [A3Antistasi/antistasiofficial#258]
We noticed that when you hire garrison for a location "local equipment" like statics at an outpost or workers at a ressource/fabric get spawned in with each garrison recruitment you issue.
So we suddenly had over ~40 statics when recruiting at the outpost next to Kavala, or had over 30 workers running around at a ressourcen when recruiting garrison.

**Comment by StefArma** [comment]
Sorry i don't understand

**Comment by StefArma** [comment]
What version are you playing? i tought i fixed duplication bug

**Comment by CurePindal** [comment]
We played on 1.7.19 yesterday and updated to B4. We couldnt confirm it on B4.

**Comment by StefArma** [comment]
1.7.19 had that bug indeed
