### ISSUE TITLE
Garrison recruitment changes, please

### ISSUE THREAD

**Issue by CurePindal** [A3Antistasi/antistasiofficial#259]
Garrison recruitment would be much less painfull when you could just set the amount + type of men you want to recruit and then issue the spawning once, instead of: 
recruit 1 person, despawn all garrison, respawn new value, wait 10 secs...
recruit 1 person, despawn all garrison, respawn new value, wait 10 secs...
recruit 1 person, despawn all garrison, respawn new value, wait 10 secs...
Very clunky...

**Comment by StefArma** [comment]
I'm alone coding and not expert, maybe a pull request? thanks ;)

**Comment by michals5** [comment]
Instead of trying to put entire FIA manpower as a garrison in 1 second and recieve 10 sec wait time, try to  wait 1-2 seconds between each soldier recruitment. Works for me.

**Comment by AlexTriada** [comment]
“wait 1-2 seconds” - not working, it’s bullsh...

**Comment by StefArma** [comment]
I'm not going to do this in the near future, and i wanna change garrisoning system anyway to direct cache anyway: recruited soldiers / reinforcements squad can be assigned as garrison once they arrive.
