### ISSUE TITLE
Skill Level

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#26]
Read this before continue: http://www.a3antistasi.com/forum/m/38173738/viewthread/29940993-antistasi-game-difficulty-explained

Barbolani idea is to give a sense of progression making the enemies stronger overtime and FIA weaker in the beginning and stronger at late stage.

In my opinion this fits perfectly in SP where reliability on AI is important and ofcourse has to be achieved by investing in Army Level. 
The problems come in Multiplayer where 10 people connect and capture bases and airports easily because of low enemy skill level at the beginning of the campaign. Balancing should be the Attacks and QRF features however we've seen they are not enoguh over a year and a half of official server gameplay.

**In multiplayer:** i'm thinking about standard skill and precision for enemies which can be tweaked only by the global coefficient set into arma game difficulty.

**Comment by AlexTriada** [comment]
Totally support, absolutely true!

**Comment by StefArma** [comment]
My proposition: make standard AI but harder for them to spot us since we're guerillas
_geninit_
0,5 skill
0,3 spot ( we can think about reduce this more, infact once you've spotted they mostly share info)
courage has to stay 1, we want them to move as a professional army, maybe bad at shooting but keep dynamic.

**if multiplayer**
_skill = **0,4;**
_unit setSkill (_skill + 0.1);
_aiming = _skill + 0.1;
_spotD = _skill **- 0.1;**
_spotT = _skill **- 0.1;**
_cour = 1
_comm = _skill + 0.1;
_aimingSh = _skill + 0.1;
_aimingSp = _skill + 0.1;
_reload = _skill + 0.1;

each skillgroup tweak +-1 according to the skillset. 

if >= 10 players in an area (too difficult to code? i think 10 players in server is fine) then precision +0,1
if >= 20 players then precision +0,2

I think i need someone expert with AI skillset to have proper numbers i did rough test 

_geninitbases_
_skill 0,5
and so on as above

_initCSAT and NATO (special forces)
skill 0,7 as usual, reducing spotD

**Comment by wurzel0701** [comment]
I would suggest a exponential tweak in the settings. I mean if we give every player a potential of 100, it wil raise linear. But multiple player (should) support each other so every connection also has potential (two can carry more, better, specific equipment). This is raising extremly fast.
1 pl => 1x 100 = 100
2 pl => 2x 100 + 1x 20 = 220
10 pl => 10x 100 + 10!x 20 = 10x 100 + 3.628800x 20 =72577000
_This may be overdramatic, at some point the potential of players working together is going to zero_

If the AI is getting exponential better with count of players, it will "force" players to cooperate, cause they got way more chance to survive when working together. It could even have an impact on performance, cause players would concentrate on a few points.

I know I´m quite new to the arma programming, but I am assuming checking how many player are attacking a specific group or base will be either extrem compley or impossible.

**Comment by StefArma** [comment]
problem is: it should check amount of player in the AO... however i can go spawn a base alone, then +10 people join me from the nearby town

**Comment by wurzel0701** [comment]
Sure, so the Skill have to be adjusted to the amount of player on the server, not the amount of player on an AO

**Comment by StefArma** [comment]
that will induce another problem tho... anyway low priority

**Comment by StefArma** [comment]
Will be variable named "enemyskill" with 0.4 standard in  1.8.1
