### ISSUE TITLE
Arsenal items lost

### ISSUE THREAD

**Issue by CurePindal** [A3Antistasi/antistasiofficial#261]
After a persistent save and restarting the server we noticed that certain items are gone (non-public server). Almost all of our MX SW 100rnd mags are gone, 2 pilot helmets we had before. Not sure if more stuff vanished.

**Comment by StefArma** [comment]
I usually have stuff adding rather than disappearing ;) anyway let's keep an eye

**Comment by StefArma** [comment]
anyone else? or more evidences?  i'd suggest to test it with inidibi2

basically you save, open the savegame with notepad and get jna_dataList
load the game, save again and compare the new jna_dataList from the save

you can also do that in game: place jna_dataList in the watch and ctrl+a in the line below
