### ISSUE TITLE
vehicle duplication glitch

### ISSUE THREAD

**Issue by jatapa2** [A3Antistasi/antistasiofficial#269]
there is an way to duplicate vehicles idk do you already know this but here it is

1. first you buy what ever vehicle you want to (statics dont work)
2. after you have bought the vehicle drive it close to your HQ and go persistent save the game
3. now go and place your vehicle to garage
4. restart the scenario
5. after restarting it will ask you "load persistent save" press yes
6. now you will see that you got car outside like you did when you persistent saved but when you open your garage you will see that the same vehicle is in there
7. now place your vehicle that was outside when you persistent saved to your garage so you can use it again (because its stuck on group after persistent save)

**Comment by StefArma** [comment]
yes, that's because garage is saved like a player stat
