### ISSUE TITLE
Can't restart mission, and no option to select difficulty or base placement at beginning??

### ISSUE THREAD

**Issue by itzPR3DATOR** [A3Antistasi/antistasiofficial#278]
Basically what the title says, I cannot restart the Antistasi mission, hoped to restart it on 'Easy' with more weapon unlocks and resources but had to delete and no restart function can be found. 

I am running the server off my PC via port forwarding so most server commands are not working, including [#restart] so I'm at a bit of a loss.

Old antistasi gave the option at the beginning to set the HQ location then difficulty etc, but now, i get nothing. It places me in at default position on hard difficulty and that's it. 

I'm running the following mods:
CBA_A3
Enhanced Movement
JSRS Soundmod
ShackTack User Interfafce
Lowgrass
Task_force_radio
Ace
Athena

Any help asap would be much appreciated.
Thanks

ADDITIONAL --------------------------------------------------------------

It seems that when I join, it is not selecting me as Commander, and my bar at the top which includes NATO support and Money does not show.

**Comment by Sparker95** [comment]
When at the role selection menu, log in as admin, go to 'Parameters' at the top right of the screen, and set an option to restart the campaign.

**Comment by itzPR3DATOR** [comment]
Thanks @Sparker95 do you know any way to set easy mode initially? I dont get any popups regarding HQ placements or difficulty setting? (not concerned with ARMA 3 default difficulties, im talking about that which affects weapon spawn in)

**Comment by Sparker95** [comment]
I understand what you mean, but sorry, I don't know. Haven't played or touched the code for a long time. I think @StefArma knows.

**Comment by StefArma** [comment]
It's same as before, after you enabled the parameter, you have the menu bottom right, there you can choose start new campaign and change from regular conditions to easy mode

**Comment by itzPR3DATOR** [comment]
Issue i had was that it wasnt setting me as commander. 

I had access to the NATO support menu, but didnt give me the option to 'start mission'.

I had to load it in LAN, then do the base selection and difficulty and then exit and host on internet.
