### ISSUE TITLE
Can't enable membership

### ISSUE THREAD

**Issue by Raptorkoda** [A3Antistasi/antistasiofficial#279]
![screenshot_271](https://user-images.githubusercontent.com/36806760/36637973-120f6186-19c6-11e8-898d-33e1f4b55a0f.png)
i have dedicated server, this problem stop my server for 3 min aprox. and have problem with the membership. on b4 work fine, but put the b7 and with parameter "on" and "off" say membership disabled. try with wiki parameters on config.cfg but same problem :c

**Comment by Sparker95** [comment]
Based on what I've read in the Internet, the 'Object not found' is not an error, just ignore it.

**Comment by Raptorkoda** [comment]
ok thanks, i try to config the membership in my sv. thanks for info to the error and sorry for my bad english
