### ISSUE TITLE
 Doubt with the parameters of config.cfg / server.cfg

### ISSUE THREAD

**Issue by Raptorkoda** [A3Antistasi/antistasiofficial#282]
I have seen the wiki on how to configure a dedicated server, but I think that the theme of the parameters is outdated, or missing parameters. I try to find those parameters so that it starts automatically when I put the autorestart.
Apologies for the bad English, is that I speak Spanish and I love your mission

**Comment by StefArma** [comment]
True, that was outdated, i changed it a bit.. anyway, tell me what you need

**Comment by Raptorkoda** [comment]
I need the parameters, to put them on the server and thus be able to configure them to start automatically with them. if you have the codes to put them in the config.cfg

**Comment by StefArma** [comment]
Which parameters?

One thing is Difficulty
Another thing is Mods or "parameters"(which is the name displayed on top right before starting mission at slot selection.

The first is about changing config.cfg
The second has to be set ingame before start the mission and they affect some mods features and the parameters are important for stuff like restarting campaign and other things.

**Comment by Raptorkoda** [comment]
not the difficulty, but the parameters of the mission itself. for example : {
AS_param_onlyPermanentMembers = 0;
AS_param_tkPenalty = 1;
};
But here they would be missing, many other new parameters that were added to the mission

**Comment by StefArma** [comment]
OK they are all inside the mission, so just start it (multiplayer ofcourse), after mission selection, you gonna be into a screen where you can pick a role but the mission isn't started yet.
You've to be admin or the host

Then check top right, there is a button called "parameters" in english click there and change stuff as you like, then press "back" and start the mission. They will be applied only for that session tho.

**Comment by Raptorkoda** [comment]
I know that it can be modified in the lobby at the beginning of the mission. but what I'm asking is if they have the codes to put it in the config.cfg so I do not have to do it in each autorestart since I'm not always connected

**Comment by StefArma** [comment]
class Params {			
AS_enableCampaignReset = 0;
AS_enableServerMember = 1;
AS_enableSwitchComm = 0;
AS_autosave = 1;
AS_saveprofilesave = 0;
AS_loadprofilesave = 0;
AS_enableVCOM = 0;
};

Theese should be the values as default.. but i did it on a hurry i'll check better tomorrow

**Comment by Raptorkoda** [comment]
ok. thanks

**Comment by Raptorkoda** [comment]
the parameters work fine, thanks again. but i have another problem. the membership dont work. i try put server member in 0 and 1. but when i enter on the server say membership disabled

**Comment by StefArma** [comment]
Strange membership is always enabled by default. 

Have you created the file in \arma3\A3Antistasi\memberlist.txt and compiled it with steamid?

76561198005296652

76561198005296652

76561198005296652

**Comment by Raptorkoda** [comment]
yep i make this .txt in same directory but nothing...

**Comment by Raptorkoda** [comment]
I have created 2 folders with the file since I am not very clear if it was in the root folder or in the arma3. but in the same way it does not work
http://prntscr.com/ikstas
http://prntscr.com/ikstas
Both have my arma3 steamID

**Comment by StefArma** [comment]
the first  one is correct, the other won't work

**Comment by Raptorkoda** [comment]
ok, meanwhile I will continue using the "fresh start" in each autostart

**Comment by zalexki** [comment]
This issue is not Antistasi code related. 
Please use the forum for this kind of questions, there is a Dedicated Server section.
