### ISSUE TITLE
Jeroen Arsenal lag

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#299]
ACE changed some categories and it resulted that misc items were found into bipod category.
So we had to fix this incompatibility issue. However after the edit of this file:

https://github.com/A3Antistasi/antistasiofficial/blob/master/AntistasiOfficial.Altis/JeroenArsenal/JNA/fn_arsenal_itemType.sqf

clickling fast to add the same item cause an annoying framedrop during the selection. 

If i revert back this file only, the lag disappear, however i have ACE items below the bipod category which is a problem anyway.

**Comment by StefArma** [comment]
Digging a bit: these lines actually are lag responsible.. however this is exactly what fixed the ACE categories...

https://github.com/A3Antistasi/antistasiofficial/blob/e08de8eaac736c0e6495f7ca748e35cbc646f1c1/AntistasiOfficial.Altis/JeroenArsenal/JNA/fn_arsenal_itemType.sqf#L61-L67

**Comment by Barbolani77** [comment]
Check the same function in WotP and see this:

//workaround for ACE bugs related to bis_fnc_itemType
if (hayACEMedical) then
	{
	if (_weaponTypeSpecific == "AccessoryBipod") then
		{
		if (_item in ["ACE_EarPlugs","ACE_RangeCard","ACE_Clacker","ACE_M26_Clacker","ACE_DeadManSwitch","ACE_DefusalKit","ACE_MapTools","ACE_Flashlight_MX991","ACE_Sandbag_empty","ACE_wirecutter","ACE_SpraypaintBlue","ACE_SpraypaintGreen","ACE_SpraypaintRed","ACE_SpraypaintBlack","ACE_RangeTable_82mm","ACE_EntrenchingTool","ACE_Cellphone","ACE_CableTie","ACE_SpottingScope","ACE_Tripod","ACE_atropine","ACE_fieldDressing","ACE_quikclot","ACE_bloodIV_250","ACE_epinephrine","ACE_morphine","ACE_personalAidKit","ACE_plasmaIV_250","ACE_salineIV_250","ACE_tourniquet","ACE_elasticBandage","ACE_packingBandage"]) then {_weaponTypeSpecific = "FirstAidKit"};
		};
	};

Thats my workaround for the issue.

**Comment by StefArma** [comment]
Thanks! some items are missing i'm testing it and checking

**Comment by StefArma** [comment]
Fixed with: https://github.com/A3Antistasi/antistasiofficial/commit/0d6534b3d4fab8597176b850c1c7fa62943d4d62 and https://github.com/A3Antistasi/antistasiofficial/commit/aaee9632a66a7cdbdc7c79f4c526267b8dba0826
