### ISSUE TITLE
ACE medical AI

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#30]
Is it possible to disable ACE medical for AI, at least enemies?

reasons:
- save a lot of performances 
- might lead to import AI revive system of WotP. 
- remove the issues of unconsciousness (like player need to shoot again downed units)

**Comment by 7akata** [comment]
Testing Antistasi (Altis FIA vs NATO for transparency)

Deleted all ACE_Medical .pbo's in order to achieve ACE mechanics with entirely vanilla Arma 3 (Antistasi) medical workings (revive, HQ crate healing, etc).

HQ crate does not heal with ACE loaded and ACE_Medical .pbo's deleted. Believe that healandrepair.sqf is the problem, and need to modify accordingly.

Change:

```
{
	if (((side _x == side_blue) OR (side _x == civilian)) AND (_x distance _posHQ < 100)) then {
		if (activeACE) then {
			[_x, _x] call ace_medical_fnc_treatmentAdvanced_fullHeal;
    	} else {
      		_x setDamage 0;
		};
	};
```
To: 

```
{
	if (((side _x == side_blue) OR (side _x == civilian)) AND (_x distance _posHQ < 100)) then {
      		_x setDamage 0;
		};
	};
```

Will test if this enables crate bypass of ACE_Medical.

**Comment by IrLED** [comment]
Looks like checking against `activeACE` is too general approach. There is additional flag [`activeACEMedical`](https://github.com/A3Antistasi/antistasiofficial/blob/c5df0b81245f3f0ca9554b796e5f91f990ab9daf/Functions/fn_detectACE.sqf#L3), which could be checked against.
i think the relevant part of https://github.com/A3Antistasi/antistasiofficial/blob/c5df0b81245f3f0ca9554b796e5f91f990ab9daf/healandrepair.sqf#L6
should look like
```
	if (((side _x == side_blue) OR (side _x == civilian)) AND (_x distance _posHQ < 100)) then {
		if (activeACEMedical) then {
			[_x, _x] call ace_medical_fnc_treatmentAdvanced_fullHeal;
    	} else {
      		_x setDamage 0;
		};
	};
```

**Comment by StefArma** [comment]
Great, then i should speed up the porting of WotP medical system

**Comment by 7akata** [comment]
Where did you find the activeACEMedical flag, and as far as I can tell there's no way to add any parameter to disable the medical system outright, which means it HAS to be deleted by the client/user, which is what's leading to the check causing issues. AKA, how does it KNOW ACE_Medical is active, which is a mission parameter (the modules are preloaded to allow people to turn ACE on and off in Antistasi transparently.

**Comment by StefArma** [comment]
Well in case it doesn't work, just a simple check if bandages are within allitems like we do for checking RHS.. it check if the AK is in the array, if not then there is no RHS

**Comment by IrLED** [comment]
@7akata 
`activeACEMedical` global var comes from https://github.com/A3Antistasi/antistasiofficial/blob/c5df0b81245f3f0ca9554b796e5f91f990ab9daf/Functions/fn_detectACE.sqf#L3
What it does - checks if there is special medical config entry (sign of med module loaded, ace_medical.pbo is loaded)
>HQ crate does not heal with ACE loaded and ACE_Medical .pbo's deleted. Believe that healandrepair.sqf is the problem, and need to modify accordingly.

Problem with the defect i found - it still tries to heal ace_medical way when there is ACE enabled(but medical might not - pbo removed), and only that case is covered with fix.

From ACE [Settings Framework](https://ace3mod.com/wiki/framework/settings-framework.html)
they have the example with `ace_medical_level`. But from the look of the ace source there is possibility to set and use `ace_medical_level=0` and disable medical(?)
https://github.com/acemod/ACE3/blob/master/addons/medical/ACE_Settings.hpp 
I will need to test that theory.

**Comment by 7akata** [comment]
Ok, got it now. If true, the Ace_Medical check would be the best route, allowing people to delete the PBO and have Antistasi check and act accordingly. Will test my way (brute force) and yours (file check) tonight.

I agree that I would believe that setting it to 0, perhaps in the 'parameters' part of mission launch would be best (maybe right above the ace revive [0,2] options) but I've worked with it for a long time and I'm just not sure if possible. In talking with people I always get the same answers, even ACE people, "It's not possible to just choose to turn it off w/o deleting." Will continue to investigate.

**Comment by IrLED** [comment]
Regarding setting the `ace_medical_level=0` as mission param. Looks like it doesn't much. ACE as the mod is loaded earlier then missio is even read, and there is a lot of integration. From mod standpoint it is close to impossible to revert that integration if mission parameter is present.

> remove the issues of unconsciousness (like player need to shoot again downed units)

Actually doing that might be punished (war-crime). Take as prisoner, heal, exchange. To AAF - for money, to NATO - for prestige, release for popularity - another resource ingame.
The check might be for shooting point-blank (<10m)

**Comment by StefArma** [comment]
Probably we'll make our own version and keep it updated without medical system
