### ISSUE TITLE
Destroying all radio towers makes zones unconquerable 

### ISSUE THREAD

**Issue by Blakmane** [A3Antistasi/antistasiofficial#311]
Once you have destroyed all radio towers in a mission, it isn't possible to capture zones (the flag changes but the map does not update and no QRF is sent).

The following error is associated with this bug:

```
Error in expression <cion] call BIS_fnc_nearestPosition;
if (getPos _antenna distance _posicion < 100>
  Error position: <getPos _antenna distance _posicion < 100>
  Error getpos: Type Array, expected Object,Location

```
And when I comment out the following code in mrkWIN.sqf, this issue is resolved:

```
_antenna = [antenas,_posicion] call BIS_fnc_nearestPosition;
if (getPos _antenna distance _posicion < 100) then {
	[_bandera,"jam"] remoteExec ["AS_fnc_addActionMP"];
};
```

So, looks like the function is searching for an antenna, not finding one because they are all destroyed, and then exiting without spawning QRF or properly handing over control of the zone to FIA.

**Comment by StefArma** [comment]
Great! thanks for that precise report, i'll check it when i'll be back!

**Comment by wurzel0701** [comment]
Pull request (#321) opened, this should fix it
