### ISSUE TITLE
Using airfield to spawn garaged aircrafts (suggestion)

### ISSUE THREAD

**Issue by michals5** [A3Antistasi/antistasiofficial#312]
I was thinking about this some time ago, it is probably too dificult but, maybe...

I know that many people are against using aircrafts and helis by players (because we are resistance and stuff), but what I dont like is idea of spawning and maintaining this sort of machinery somewhere on the hills or in forest. Also if you capture some aircraft, but your HQ is in area that prohibits you to land, you cant have it.

How about spliting garage in to land and air based vehicles, with air garage being deployed on airfield (or perhaps even some flat ground in the field) that player chooses (similar to deploying roadblock). It would make recovering of aircrafts much easier, while not dangering HQ by someone, who fails his landing. Air garage could serve as fast travel point as well. Also, it would limit usage of aircrafts if you dont own any airfield and give FIA airfield some real usage (outside nato support).

I also think that armament on vehicles is overused in antistasi (source of fuel is well known, but where are we geting unlimited suply of free-fall bombs and 125mm tank shells is mystery to me), but that is different topic.

**Comment by StefArma** [comment]
definitley make sense, however in my last WiP pull request https://github.com/A3Antistasi/antistasiofficial/pull/301 i just removed the planes considering it's illogical FIA can use them without having other planes countering and, nevertheless, they cause serverlag because quick cache and decache of enemy places.

**Comment by wurzel0701** [comment]
Serverlag is mostly solved and counter jets are WIP, so your idea perhaps will be real in the future

**Comment by zalexki** [comment]
This is not code related, please use proper section forum for suggestions.
http://a3antistasi.enjin.com/forum
Thanks for your understanding.
