### ISSUE TITLE
UnlockedWeapon check replacement

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#32]
Since 1.7.6 unlocks are no longer counted because of Jeroen Arsenal which is limited. 
Consider the amount of checks on unlockedWeapons it's important to find a solution.

There are two options:
A) Change "unlockedWeapons" to "AvailableWeapons" so that, reached the thereshold in the Arsenal, AI can dispose of those weapons.
B) Remove all the unlockedWeapons checks and replace them with new ones.

Barbolani tweaked it on WotP in order to have unlock again.. however in that way the whole work of Jeroen is a bit wasted.

Main affected things:
- Friendly AI recruit and garrison
- AAThreatEval and landThreatEval
- scoreneeed in fn_spawnAttack
- Missionrequest gearcount
- \Municion\rewardCrate.sqf
- ArmyLevel progression (now disabled)

**Comment by AlexTriada** [comment]
Variant A

**Comment by MAGA05REGION05** [comment]
Привет ребята,хочу прежде всего сказать спасибо за сделанную вами работу. На счет арсенала хотел сказать следующее,с учетом того что оружие не становится бесконечным теряется смысл его сбора с поля боя и ящиков.Пока вы будете исправлять арсенал,а это неизвестно когда будет хотел бы поделиться с вами некоторыми мыслями.Говорю заранее что не разбираюсь в языках программирования поэтому не серчайте если сказал глупость.Итак нельзя ли сделать так что бы оружие можно было купить у сумасшедшего ирландца пусть за большие деньги,но что бы стало неограниченным,пусть в начале будут открываться слабые стволы,прицелы,снаряжение и прочее. Не знаю на сколько это трудно для вас может вообще не возможно,но хотел предложить эту мысль так как в связи с последними версиями миссии из за багов интерес к этой миссии угасает у многих.Еще раз спасибо вам за проделанную работу.

**Comment by StefArma** [comment]
For the option A, Sparker gave me a good hint to start from:

availableGears = []; 
{ 
    _gears = _x; 
    _enoughgears = _gears select {_x select 1 > 25}; 
    { 
        availableGears pushBack (_x select 0); 
    }forEach _enoughgears; 
} forEach jna_datalist;

**Comment by StefArma** [comment]
How friendly AI pick weapons:

Units are initialized calling randomrifle
https://github.com/A3Antistasi/antistasiofficial/blob/dafb407d4b7e298ae08190eb5b2c86bb48521e1d/AntistasiOfficial.Altis/Functions/fn_initialiseFIAGarrisonUnit.sqf#L38-L39

randomrifle check into the unlocked weapons
https://github.com/A3Antistasi/antistasiofficial/blob/dafb407d4b7e298ae08190eb5b2c86bb48521e1d/AntistasiOfficial.Altis/Municion/randomRifle.sqf#L43-L51

unlocked weapons are defined from JNA as all possible items
https://github.com/A3Antistasi/antistasiofficial/blob/dafb407d4b7e298ae08190eb5b2c86bb48521e1d/AntistasiOfficial.Altis/Functions/fn_JNA_pushLists.sqf#L29-L33

We can add extra conditions to this file.. for istance get from the list only the ones which are >n

**Comment by vodas3** [comment]
I would rather recommend letting the ai only use the weapons where there is enough weapons and ammo as well so your ai wont use some rare thing u are saving whole game :D

**Comment by alexUnd** [comment]
I really expect this function - when the AI can take the trunks automatically from the arsenal. I dig a long time but I could not find how to reduce the number of weapons after it gets AI. Therefore, to simulate the receipt of sometimes items that are in the arsenal, I did based on a randomization, which depends on Army XP level`if (_changeRifle) then {
	if (random 25 < _skillFIA) then {
		_useRifle = ["primary"] call AS_fnc_JNA_getLists;
		_unit removeMagazines (currentMagazine _unit);
		_unit removeWeaponGlobal (primaryWeapon _unit);
		_newRifle = selectRandom _useRifle;
		if (_newRifle in genGL) then {
			_unit addMagazine [guer_gear_GL_gren, 1];
			_unit addMagazine [guer_gear_GL_gren, 1];
			_unit addMagazine [guer_gear_GL_gren, 1];
			_unit addMagazine [guer_gear_GL_gren, 1];
		};
		[_unit, _newRifle, 8, 0] call BIS_fnc_addWeapon;
		_items = [unlockedOptics,["optic"] call AS_fnc_JNA_getLists] select activeJNA;
		if (count _items > 0) then {
			_compatibleOptics = [primaryWeapon _unit] call BIS_fnc_compatibleItems;
			_options = [];
			{
				if (_x in _compatibleOptics) then {_options pushBack _x};
			} forEach _items;
			_unit addPrimaryWeaponItem (selectRandom _options);
		};
	} else {
		_unit removeMagazines (currentMagazine _unit);
		_unit removeWeaponGlobal (primaryWeapon _unit);
		_newRifle = selectRandom unlockedRifles;
		if (_newRifle in genGL) then {
			_unit addMagazine [guer_gear_GL_gren, 1];
			_unit addMagazine [guer_gear_GL_gren, 1];
		};
		[_unit, _newRifle, 4, 0] call BIS_fnc_addWeapon;
		if (random 6 > 3) then {
			_items = [unlockedOptics,["optic"] call AS_fnc_JNA_getLists] select activeJNA;
			if (count _items > 0) then {
				_compatibleOptics = [primaryWeapon _unit] call BIS_fnc_compatibleItems;
				_options = [];
				{
					if (_x in _compatibleOptics) then {_options pushBack _x};
				} forEach _items;
				_unit addPrimaryWeaponItem (selectRandom _options);
			};
		} else {
			_items = unlockedOptics;
			if (count _items > 0) then {
				_compatibleOptics = [primaryWeapon _unit] call BIS_fnc_compatibleItems;
				_options = [];
				{
					if (_x in _compatibleOptics) then {_options pushBack _x};
				} forEach _items;
				_unit addPrimaryWeaponItem (selectRandom _options);
			};
		};
	};
};`

**Comment by alexUnd** [comment]
found how to reduce the number of prelets in the arsenal. BUT when there are 000 items, they can still be taken.
`if (_changeRifle) then {
	_useRifle = ["primary"] call AS_fnc_JNA_getLists;
	if (count _useRifle > 0) then {
		_newRifle = selectRandom _useRifle;
		_unit removeMagazines (currentMagazine _unit);
		_unit removeWeaponGlobal (primaryWeapon _unit);
		[_unit, _newRifle, 8, 0] call BIS_fnc_addWeapon;
		[_newRifle,"primary",1] call AS_fnc_JNA_removeItem;
		_updated = ["primary"] call AS_fnc_JNA_pushLists;`

**Comment by alexUnd** [comment]
somebody tell me how to make an array _result from an array _useRifle. In array _result must be that weapon the number of units of which in the arsenal > 1
if (_changeRifle) then {
_useRifle = [["primary"] call AS_fnc_JNA_getLists] - [unlockedRifles];
if (count _useRifle > 0) then {
?????**# _result = {count (jna_dataList select _useRifle) > 1} in _useRifle;**?????
_newRifle = selectRandom _result;
_unit removeMagazines (currentMagazine _unit);
_unit removeWeaponGlobal (primaryWeapon _unit);
[_unit, _newRifle, 8, 0] call BIS_fnc_addWeapon;
[_newRifle,"primary",1] call AS_fnc_JNA_removeItem;

**Comment by StefArma** [comment]
How about showing a branch with those codes in a proper .sqf? i think that gonna be easier to read :)

Looks great, just a bit busy theese days

**Comment by Sparker95** [comment]
Thank you for your contribution with this issue!
Once you are confident about your solution, you should make a pull request and we will easily check it out.
For now i suggest you to do these things: make a separate branch in github for these changes and commit to it. Don't forget to push it to github so that we can see the changes. When you're done, you can make a pull request.
If you have problems, write to me and i will try to help:
http://steamcommunity.com/profiles/76561197981549243/
I'm also new to github, but i'm sure that's not the way we are supposed to share code.

**Comment by Sparker95** [comment]
What exactly is the problem with AIs taking weapons right now? Is there even a problem or is something broken?
Currently AIs take random primary weapons that are above certain threshold defined here:
https://github.com/A3Antistasi/antistasiofficial/blob/5846f32eec12ac3e08ac081c0f2f4306135baf08/AntistasiOfficial.Altis/Lists/gearList.sqf#L1134-L1138
It seems to be working fine. Maybe we should add an extra check to prevent them from taking default bad weapons if theare are better ones available?

**Comment by StefArma** [comment]
i wasn't aware of that threshold

**Comment by Zlipentax** [comment]
Hi,

Just want to make a suggestion. Can we make AI taking weapon with the highest amount of quantity in Arsenal? For example AK74- 13 unit, AK103-15 unit. So AI will take AK103  and we can control which weapon that we want AI to take based on the quantity . I saw a command selectMax in Wiki but I do not know what variable that Antistasi use to count amount of weapon in Arsenal. Sorry I am not a professional programmer .

**Comment by Barbolani77** [comment]
In the times before arsenal, where the only ammobox was.... the ammobox, I made the following.

Make arrays of available weapons in the ammobox, update every tick (resourcecheck), put in those arrays only classnames which have a big number of items.

Make some bools for unlocked things like radios, NV, those kind of things.

On spawning units, pick a random classname as the array was totally "crude" the more of a classname, the more possibilities of having that weapon spawned or pick one of the basics to be sure the AI has

If the bools are true, add / dont remove items.

But to be honest, I think you are making a mistake here, unlocking is cool, is the achievement feel which lots of people love.

**Comment by zalexki** [comment]
Totally agree with @Barbolani77, unlock achievement was a big deal for my group, this should be some kind of easy in game configuration at first start of the mission.

According to the last @Sparker95 explanation everything seems sorted out and working as expected in the code. 
I'm closing this, feel free to continue the discussion on the [forum](http://a3antistasi.enjin.com/forum) where it belongs.
