### ISSUE TITLE
RHS not recognized on startup

### ISSUE THREAD

**Issue by TheNewUprising** [A3Antistasi/antistasiofficial#329]
When launching server on dedicated private server, RHS fails to be recognized and in turn the weapons are not showing up except in admin Arsenal. Also Ai are not using RHS gear just vanilla GreenFor gear.

**Comment by StefArma** [comment]
Hello!

I'm afraid this is far from beeing an useful bug report, i'd suggest to read this first https://www.reddit.com/r/A3AntistasiOfficial/comments/8dpr9y/rpt_how_to_readuse/
