### ISSUE TITLE
Vehicles Duplicating in Garage

### ISSUE THREAD

**Issue by itzPR3DATOR** [A3Antistasi/antistasiofficial#351]
Started when we put a pickup in our garage, after that we now have unlimited pickups and they cannot be removed from garage, in addition to this, these pickups actually fill up the garage meaning we cannot add new vehicles.
It also occurs that if you take a vehicle out of the garage and try to put it back in straight away, you cannot as it says the garage is full. 

Now EVERY vehicle has started duplicating including trucks, helicopters, APCs and IFVs.

(Pickup is being used in place of the in-game item 'Offroad')

**Comment by Sparker95** [comment]
Hi! I assume this bug is related to the Antistasi 1.2 version, right? Because you have created a similar issue there as well: https://github.com/A3Antistasi/A3-Antistasi/issues/151

**Comment by itzPR3DATOR** [comment]
Sorry @Sparker95 it's the most recent Antistasi, im new to github and this thread and wasnt sure where to post it. The version available on Steam which updates regularly (not sure it that one is 1.2 or not)

**Comment by zalexki** [comment]
both repositories have description ;)
