### ISSUE TITLE
Mission Crate instead of Vehicle

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#45]
I think a crate/box is way more logic for a delivery mission because it can be moved from a vehicle to another and allow naval transportation as well which would be perfect for Tanoa. 

EDIT: i've tested by barely replacing the truck with a crate, if i teleport the crate in the good position the mission will run correctly. 

So now we've just to choose the crate and to be sure we can move it by
- loading in car
- slingload
- ACE intetraction (this might be difficult because i don't know what happend to the id while it's stored)

EDIT2:
I tested with Box_East_AmmoVeh_F  that box, regardless is the wrong skin etc. can be loaded into the offroad with Jeroen function and when i arrive at destination it works.
the only downside is that it won't be able to check its position while into the offroad so we should add a script that force unload from the car or anyway that don't make the mission running if that is still loaded into the car.

**Comment by Sparker95** [comment]
Damn that's a great idea! It would be not hard to do with our existing logistics script.
We should find a different-looking crate for missions and update the crates and vehicles database in the logistics part to make it work.

**Comment by IrLED** [comment]
Thing is that crates should somehow give a hint, which they belong to. Currently when getting in the truck, there is a hint, what to do with the content.

**Comment by StefArma** [comment]
addaction "check delivery info"

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/commit/e9123642ce0de662b2d596a519c1f04513b1249f This works like a charm.

Now it's good for testing, maybe aestethic could improve... the CSAT vehicle ammobox isn't really the aspect of civilian supply deliveries.. any other idea which is compatible with Sparker cargo animation is good!

**Comment by StefArma** [comment]
Land_PaperBox_01_small_closed_brown_IDAP_F
Land_PaperBox_01_small_closed_brown_food_F
Land_PaperBox_01_small_closed_white_IDAP_F
Land_PaperBox_01_small_stacked_F

I'm looking to implement theese instead of that horrible ammobox. The big one would replace the ammobox easily, the 3 smalls could let a variant similar to the leaflets, 3 crated for 3 different locations... let's see..

**Comment by StefArma** [comment]
Updated with https://github.com/A3Antistasi/antistasiofficial/commit/767cd37e0210985f6fca0f739e5ddae6cbe7dd95 now the box is from IDAP, won't be shared with bank robbery and you can load it into boats or trucks

**Comment by StefArma** [comment]
Wasn't working untill this fix https://github.com/A3Antistasi/antistasiofficial/commit/eb78a4a509331e0cd8d1565a468506d99dd2d453

Now some finish is required:
- make mission running only when crate is unattatched
- change skin at mission completed changing it in an empty crate

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/commit/e5705258b094cc85fb15529b7c1a8653cc815ad4 Supply Recovery is now improved: IDAP empty crate (can't be loaded) untill the small crates get repacked (disappear after timer) then a filled crate model replace the empty one.
This filled crate can be loaded into a truck and delivered to population

Missing the addaction to tell players where to bring it when looking at it

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/commit/92827da107e0ba3ed46ac0eed998098eecdd04ca reduced timer for supply delivery

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/commit/3a1c97feeeea861ffe0e72627801839e47966a2a improved text string

**Comment by StefArma** [comment]
Fix of several errors
https://github.com/A3Antistasi/antistasiofficial/commit/23c3a05f188035a7c4a8c014f02ebff7f3c7b97b

sorry for the huge delay
