### ISSUE TITLE
AI driving speed

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#46]
I'm wondering if the driving speed reduced  (is it possible) could fix some issues and make them more reliable and less dangerous.

**Comment by 7akata** [comment]
From [the wiki ](https://community.bistudio.com/wiki/limitSpeed) (this is old but I bet the syntax still works, I just dont know about how to apply it to the current civilian spawning system).

```
// Adjust "speedLimit" variable to change limited speed. (A3 1.24 we don't need loop for a continus effect, limitSpeed alone is enough.)
_this setVariable ["speedLimit", 200];
_nul = _this spawn {
	while {canMove _this} do {
		_this limitSpeed (_this getVariable "speedLimit");
		sleep 0.1;
	};
};

```

**Comment by StefArma** [comment]
Can you make a pull request for this?

**Comment by IrLED** [comment]
@StefArma 
Another `spawn` with short pause - performance eater. Better leave civ-AI on foot and use saved CPU for mil-AI. I don't like this particular solution.

**Comment by StefArma** [comment]
https://forums.bistudio.com/forums/topic/191515-ai-driving-feedback-topic/

This article suggest for test purpose to do:
driver vehicle forceSpeed 40;

so the driver only has frocespeed and when the vehicle is taken by player it won't have any limit.

**Comment by IrLED** [comment]
The actual code in AS
https://github.com/A3Antistasi/antistasiofficial/blob/master/AntistasiOfficial.Altis/CREATE/createCIV.sqf#L127
Also from the forum post looks like `forceSpeed` is applied to AI driver, `limitSpeed` is applied to vehicle. We've been applying `limitSpeed` to vehicle.
Description and examples on wiki are confusing
https://community.bistudio.com/wiki/forceSpeed
https://community.bistudio.com/wiki/limitSpeed

**Comment by IrLED** [comment]
Also observing AI for some time (including civ) i don't see the need to any special limitations (driving speed is ok imho)

**Comment by StefArma** [comment]
yes after last update they looks way smarter

**Comment by StefArma** [comment]
Not a thing anymore
