### ISSUE TITLE
CBA dependency & TFAR default frequencies

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#5]
As far as i tried, the only way to keep radio frequencies sync for default channels is to have a dependency on CBA.

If anyone knows how to make it possible without the dependency would be very nice to know!

Also, even if i've set
TF_same_lr_frequencies_for_side = true;

LR radio keep having different frequencies on different players which is annoying considering that accessing the arsenal reset those causing LR comms issues.

**Comment by DukeVenator** [comment]
Did you try adding the tfar modules for eden into the world?
not the cba ones the tfar ones

**Comment by StefArma** [comment]
Yes, and then you've TFAR dependency which is worst than CBA one.
Also, TFAR settings are somehow overwritten by CBA, that's why at some point we had frequencies unsync.. TFAR had the sync on but CBA didn't.

**Comment by DukeVenator** [comment]
Interesting did not know that? 
hmmm asked around
https://github.com/michail-nikolaev/task-force-arma-3-radio/wiki/API%3A-Variables

"Is there any workaround for this? I have tried using the TFAR API but it seems that the functions don't really work when the player joins (using TFAR_fnc_setPersonalRadioFrequency in a script in the init line of a player)." 

the response from the devs was try to set values via script: (tf_freq_west and other)

These ones in particular looked interesting

FAR_defaultFrequencies_sr_independent                                Sets the default frequencies for Independent Short-Range Radios. Also sets tf_same_sw_frequencies_for_side = true;. | Server | Random value.
-- | -- | --
TFAR_defaultFrequencies_lr_west                                  Sets the default frequencies for BLUFOR Long-Range Radios. Also sets tf_same_sw_frequencies_for_side = true;. | Server | Random value.
TFAR_defaultFrequencies_lr_east                                  Sets the default frequencies for OPFOR Long-Range Radios. Also sets tf_same_sw_frequencies_for_side = true;. | Server | Random value.
TFAR_defaultFrequencies_lr_independent                                  Sets the default frequencies for Independent Long-Range Radios. Also sets tf_same_lr_frequencies_for_side = true;. | Server | Random value.

**Comment by StefArma** [comment]
I've set only CBA ones into cba_settings.sqf the others i don't know where to place them

**Comment by AlexTriada** [comment]
I set this in the server settings in the start of the mission

**Comment by AlexTriada** [comment]
And after that, this settings save in th var file in the profiles

**Comment by StefArma** [comment]
To remove cba dependency you've to edit the .sqm removing

https://github.com/A3Antistasi/antistasiofficial/blob/2ad1d76b0b1320cb55110c1d6f71563cb65505ce/AntistasiOfficial.Altis/mission.sqm#L37

https://github.com/A3Antistasi/antistasiofficial/blob/2ad1d76b0b1320cb55110c1d6f71563cb65505ce/AntistasiOfficial.Altis/mission.sqm#L97-L123

**Comment by StefArma** [comment]
Since CBA update 3.5.0.171204 the channels are not synched with the same radio frequency

**Comment by IrLED** [comment]
I think TFAR update should supposedly fix it.

**Comment by StefArma** [comment]
TFAR isn't updated since long, actually the current TFAR updated version is on github only and has incredible improved functionalities, the problem is it's gonna be required arma3sync instead of the handy steam download.

**Comment by AlexTriada** [comment]
Why are you dont close this issue?
"As far as i tried, the only way to keep radio frequencies sync for default channels is to have a dependency on CBA.
If anyone knows how to make it possible without the dependency would be very nice to know!"
- as i say, i know how!!!
"I set this in the server settings in the start of the mission, and after that, this settings save in the var file in the profiles" - are you read this?
Or you dont understand? If you are not - signal somehow

**Comment by AlexTriada** [comment]
Ok, do this steps:
1. Start the server
2. Go to the server with arma 3 client 
3. Enter as admin
4. You are in lobby
5. Press next you see this
https://steamuserimages-a.akamaihd.net/ugc/893267009192996078/33B5A86B63BF29B30BDBD6DB0F25CBE0B07DF533/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C2048%3A1152&composite-to=*,*%7C2048%3A1152&background-color=black
6. Press CONFIGURE ADDONS you see this
https://steamuserimages-a.akamaihd.net/ugc/893267009192996193/EBF4EC2550D9E35E1BCAB05D019448C49BFB7A1D/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C2048%3A1152&composite-to=*,*%7C2048%3A1152&background-color=black
7. set overwrite mission
https://steamuserimages-a.akamaihd.net/ugc/893267009192996826/6FDEEF2CDE8B4781CECB5F200449678299024692/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside%7C2048%3A1152&composite-to=*,*%7C2048%3A1152&background-color=black
8. press OK

**Comment by StefArma** [comment]
Oh wow awsome!!! Thanks! I'm going to add this to the wiki ok?

**Comment by AlexTriada** [comment]
ОК))

**Comment by AlexTriada** [comment]
Maybe you will need to save the configuration of the server, so don’t forget press save and chusing configuration save of the server
