### ISSUE TITLE
Fuel Scarcity

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#53]
I proposed this long time ago, now thanks Dusty for reminding me.

Visiting a gas station and refuel is a working feature however noone ever needed it.

What i propose is to setfuel 0,05 to all civilian vehicles by default, same with purchased vehicles.
Also setFuelCargo to 0 to fuel trucks, so that they're useful only if you go replenish them, maybe by adding a cost. 

About enemy vehicles i'd say to set it at 0,3, infact they have bases and it's useless to keep all the fuel in a combat vehicle which might explode during gunfights. 

Tell me what do you think, and also i need help where to place this code... maybe in VEHinit.sqf

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/commit/830ca25515537c0be6be7b72874c22d3579d4580

Applied by this.

Let's see if it require an extra balance...

For istance i'd say that heal repair and rearm should check how much fuel there is, and if <0.01 then setfuel 0.01 that is enough to move the vehicle a bit and visit a fuelstation
Since biki is under maitainance i don't know the commands to make this check.

Another thing to check is the attacking helicopters, i don't want them to fall down because of no fuel... i've run some distance test and they were fine in VR.. let's see in game

**Comment by StefArma** [comment]
From my measurement: 
vanilla truck and littlebird both with setfuel 0.1 can travel for 40km regardless the difference one is helo and the other is a truck.

in termns of scarcity i think that 0.1 is a lot considering altis is 22km wide.. so values will be adjusted between 0.01 and 0.1

**Comment by StefArma** [comment]
Tested RHS Mi-8 with 0.1 = 33km for a total 10min of travel... ok i set helos to 0.2

**Comment by Sparker95** [comment]
Could you give helicopters and planes more fuel?
Noone would fuel up an attack helicopter only enough for a way to the target and back, considering the biggest distance it would need to fly with Altis map. Especially if you can fuel it up more.
It might need to fly around and circle for a while.
Also IDK if Arma simulates it right, but IRL hover mode consumes much more helicopter's fuel than a straight flight.

**Comment by StefArma** [comment]
Good point Sparker, then i'm setting it to 60%, more than enough i think

**Comment by StefArma** [comment]
Right now it works for vehicle purchased
for some enemy vehicles

it doesn't work for civilians, regardless i added the fuel reduction both in civVEHinit.sqm and createciv.sqf...

need help!

**Comment by StefArma** [comment]
Fixed civi fuel https://github.com/A3Antistasi/antistasiofficial/commit/175c69f0463c73abeaa0ab8d777e8198c54839ec

ACE give values on fuel: 
setfuelcargo = 0.01 = 2000 liters and a sport car empty took 80 liters to be filled.

I'll start with this value but i might consider to reduce the amount of fueltrucks cargo more and add options to the seaport to get a fuel resupply.

**Comment by StefArma** [comment]
An Mi-8 need 3800 liters to fill.

**Comment by StefArma** [comment]
Have to check garage for saving fuel amount

**Comment by StefArma** [comment]
This make Garage saving fuel and fuelcargo
Fixed the fuelcargo when ace is active, set 300 ACE liters (car is filled by 60 liters and heli with 3200)
we might tweak again the amount of liters by default.

https://github.com/A3Antistasi/antistasiofficial/commit/39e8070cd1906f46acf8dcca535e05af6184fc21

**Comment by StefArma** [comment]
Civi cars have random amount of fuel to max 50% https://github.com/A3Antistasi/antistasiofficial/issues/136

**Comment by StefArma** [comment]
Changed mission to: Steal or destroy Fuel Truck https://github.com/A3Antistasi/antistasiofficial/commit/ba15edb77026540f4e117884019eded7ce117a30

**Comment by BlackburnUTG** [comment]
ACE: need to implement the ability to refuel cargo of refuel-truck

**Comment by StefArma** [comment]
i was thinking to allow refuel it at factories

**Comment by zalexki** [comment]
You can refuel heli at least at chalkia and some other cities too.
Actually it seems we can script it. 
https://community.bistudio.com/wiki/setFuelCargo

Scenario:
I am at position _sameRadiusAsFuelNozzle of a Fuel Station
And i am in a Fuel Truck
And I have engine off
And I wait 5s
Then CargoFuel will tick X liters every X 

@A3Antistasi/contributors ?

**Comment by StefArma** [comment]
Yes we can script it, as i used that command to save the fuel amount in garage.

I reopened the issue because of vehicles nearby HQ, those are saved just as classname and they get fresh spawned (so repaired, fully rearmed, and fully refueled) when game load.
