### ISSUE TITLE
Headless Client assignement

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#54]
1HC = it takes the load of HCattack,HCgarrison,HCciviles.
2HC = 1HC takes HCattack, 2HC take garrison and cibiles
3HC = 1 HC = attack, 2HC = garrison, 3HC = civis

- HCattack: patrolCA, NATO, enemy supply convoy, CSAT HQ attack, defend camp, AAF attack, propaganda.
- HCgarrison: all FIA markers, NATO roadblock and garrison units, AS_specOP, AS_Oficial (some missions)
- HCciviles: civilians 

As you can see  they are unbalanced, HCattack has the most units.. so i'm trying to think it another way.

I can't see where are recruited units assigned to, and anyway, i would like to assign at least some units also to the server, maybe the Attack which is never more than 50 units which are anyway 25% of the max capabilities of an headlessclient.

**Comment by StefArma** [comment]
Awsome, how is roundrobin balancing units among HCs by the way? i haven't seen any check in the code

**Comment by GlennMey** [comment]
Are you talking about the script version or ACEX? If so both versions are using a check that runs every 1 minute to check that the Headless clients have AI's to process. Atleast the script version has it, seen here:
rebalanceTimer = 60;  // Rebalance sleep timer in seconds
 // If load balance enabled, round robin between the HCs - else pass all to HC
    if ( _swap ) then {
      _rc = false;

      if ( _loadBalance ) then {
        switch (_currentHC) do {
          case 1: { _rc = _x setGroupOwner _HC_ID; if (!isNull HC2) then { _currentHC = 2; } else { _currentHC = 3; }; };
          case 2: { _rc = _x setGroupOwner _HC2_ID; if (!isNull HC3) then { _currentHC = 3; } else { _currentHC = 1; }; };
          case 3: { _rc = _x setGroupOwner _HC3_ID; if (!isNull HC) then { _currentHC = 1; } else { _currentHC = 2; }; };
          default { diag_log format["passToHCs: [ERROR] No Valid HC to pass to.  _currentHC = %1", _currentHC]; };
        };
      } else {
        switch (_currentHC) do {
          case 1: { _rc = _x setGroupOwner _HC_ID; };
          case 2: { _rc = _x setGroupOwner _HC2_ID; };
          case 3: { _rc = _x setGroupOwner _HC3_ID; };
          default { diag_log format["passToHCs: [ERROR] No Valid HC to pass to.  _currentHC = %1", _currentHC]; };
        };
      };

I have no experience in coding what so ever but as i understand it, its passing AI's in a in perfect scale as I see it on my cpu usage, its about 100% in a good battle, and we're usually just 3 people on the server. This is with 3 headless clients on the same server with affinity options. Such as 1 HC = 1 core.

**Comment by StefArma** [comment]
roundrobin is in ACEX so i think is the same... my question is How it checks. 

Is it FPS check? count unit check?

**Comment by Sparker95** [comment]
If I understood correctly, you can't pass a unit to one HC and another unit from the same group to another one. At least the scheduler mentioned above passes whole groups to HCs.
As for sharing, it seems to share the groups equally between all the HCs, that's why it's called Round Robin. Looks rational to me.
If we want to share units even more equally, we can rearrange lists of groups passed to HCs based on number of units in every group, so that all HCs get equal amount of units, but a straightforward algorithm on how to do it doesn't come to my mind now.

**Comment by GlennMey** [comment]
There is no check this happens automatically, if a group is bound to the server it gets spread evenly out to the HC's.

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/pull/146 IrLED you're great

**Comment by StefArma** [comment]
Done with this: https://github.com/A3Antistasi/antistasiofficial/pull/146 Immense thanks to IrLED
