### ISSUE TITLE
Autoheal makes AI subordinate stuck

### ISSUE THREAD

**Issue by IrLED** [A3Antistasi/antistasiofficial#56]
When Autoheal is enabled subordinates get stuck if they were hit and performed autoheal.
Possible steps to reproduce:
Hire squad member, Ymenu->AI mngmt->AutoHeal(green)
After engagement if unit was hit(being in prone position), he performs autoheal (weap is holstered to the back). After heal weap is not back to hands, unit irresponsive to commands.

**Comment by StefArma** [comment]
Is this the same problem that now when AI squads are recruited are stuck untill you move the driver in and out? I'll test... infact AutoHeal is enabled by default

**Comment by StefArma** [comment]
Lack of evidences
