### ISSUE TITLE
Reading an external file to list members

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#6]
Coding into the mission the members is not optimal, however that's the only way i know so far.

Would be nice to know if is possible to read a file stored into the server folder that include the IDs of members so that each server can set their own members and avoid useless waste of time in adding people manually all the time.

**Comment by DukeVenator** [comment]
I'll ask quiksilver the guy behind invade and annex 
he has this cool member system

**Comment by DukeVenator** [comment]
had a chat with him and a few other modders they say it could be possible if the mission system was expanded with the ability to access non mission files but at the moment he is got a hard code members list.
I don't its possible at this time:(

**Comment by MooseAteJack** [comment]
Have you had a look at A3Wasteland? That launches with calls to files in a local folder to override configurations in the mission file so you can update config without repacking .pbo

Uses variations on this kind of thing:

`if( loadFile(configFile) != '' ) then
    call compile preprocessFileLineNumbers (configFile);`

May be adaptable

**Comment by StefArma** [comment]
I checked A3wasteland but i can't find any references where it compile a path that is outside the .pbo, could you be more specific? I'm very interested

**Comment by IrLED** [comment]
I think it's generally a bad idea to store playerUID to publicly accessible files. Starting from Arma3 those are not anonymized GUIDs but ids directly related to steam profiles (try http://steamcommunity.com/profiles/[playerUID ]) - **BAD**. What could be the solution - external member list is stored into serverside mod (in exploded form, not really the mod but data storage) and read into arma with `loadfile` and `@` notation (https://forums.bistudio.com/forums/topic/175141-loading-settings-from-external-files/). That's the read part. To save content - external tool (web registration) has access to the exploded content of the server mod. Then ingame that file is reread (periodically, on admin action, on restart). That's how it might work.

**Comment by AlexTriada** [comment]
Who are talking about the "publicly accessible files"? "a file stored into the server folder' is not the "publicly accessible file"

**Comment by AlexTriada** [comment]
mission "Liberation" is already have this system member list in external file

**Comment by IrLED** [comment]
@AlexTriada 
about publicly accessible files: anyone who connects to the server downloads the mission `.pbo` to `MPMissionCache` dir. With some tools that file is exploded and content of `orgPlayers/mList.sqf` is exposed.
E.g.
 ```
...
"76561198005296652",  	//Stef
...
"76561198070770670", //DustinPeak
...
```
http://steamcommunity.com/profiles/76561198005296652
http://steamcommunity.com/profiles/76561198070770670

It requires some (publicly available) knowledge to perform that, but still i doubt it's the good idea to expose that info.

**Comment by IrLED** [comment]
And also do i want (as the workshop subscriber) allow all those people be commanders on my private server(backdoor access), when i just host **_official antistasi_** version.

**Comment by IrLED** [comment]
@AlexTriada 
I checked [Wyqer's KP_Liberation](http://steamcommunity.com/sharedfiles/filedetails/?id=878714108) [GitHub repo](https://github.com/Wyqer/kp_liberation).
The mission utilizes the persistence via `profileNamespace` (see [scripts/server/game/save_manager.sqf](https://github.com/Wyqer/kp_liberation/blob/7fbe77078ec6f415756e4a3a0f9cb97357118ff4/Missionframework/scripts/server/game/save_manager.sqf#L450) lines 450-630)

That correlates with
>Another solution - to make members list the part of profileNamespace, as it now stores players loadouts and campaign progress.

**Comment by IrLED** [comment]
My findings so far
Loading from external file is possible, but starting from [ARMA3 1.52](https://dev.arma3.com/post/spotrep-00048) 
>Changed: Script commands loadFile*, htmlLoad, prepocessFile*, exec* now consider file patching settings

Official discussion https://forums.bistudio.com/topic/183049-file-patching/

That behavior can be controlled/overriden by [cmd option -filePatching](https://community.bistudio.com/wiki/Arma_3_Startup_Parameters#Developer_Options) and [server.cfg setting allowedFilePatching](https://community.bistudio.com/wiki/server.cfg)

[A3Wasteland external loading code](https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/7cfab4794c3a73300b63602bfddc05ae2e11b0e7/server/init.sqf#L15)

Legacy instructions to enable external configuration - https://github.com/A3Wasteland/Release_Files/blob/master/IMPORTANT.txt - doesn't work as is from 1.52+

Other projects on GitHub using external loading - https://github.com/search?q=isFilePatchingEnabled&type=Code&utf8=%E2%9C%93

**Comment by AlexTriada** [comment]
Idea! Server.cfg - params, look on to that

class Missions
{
	
	class Antistasi
	{
		template = "Antistasi.lythium";
		difficulty = "Custom"; // "Recruit", "Regular", "Veteran", "Mercenary"
			class Params
			{
				members = [1st_ID... , 2nd_ID... , 3rd_ID... ];				
			};
	};
};

mb this metod?

**Comment by IrLED** [comment]
research is done
