### ISSUE TITLE
ACE 3.11.0 issue on new campaign

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#60]
After this ACE update of today, starting a new mission cause no ACE items into the Arsenal.

**Comment by StefArma** [comment]
This is the only intel i have
https://github.com/acemod/ACE3/pull/5502

**Comment by IrLED** [comment]
I was testing the issue locally, and it worked without the issue. Along the way the pull-request was created to enhance ace detection (proper ace way) #63 
DS and client were using ACE ver. 3.11.0.26
From debug console local execute `systemchat format["ACE version: %1", [] call ace_common_fnc_getVersion];`
for server execute `diag_log format["ACE version: %1", [] call ace_common_fnc_getVersion];` and check rpt

**Comment by IrLED** [comment]
my bad, i missed the part about starting a new campaign. Now i see the effect.

**Comment by IrLED** [comment]
See https://github.com/A3Antistasi/antistasiofficial/issues/64#issuecomment-339440442
