### ISSUE TITLE
Balancing Vanilla

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#62]
The main reason that players prefer RHS instead of Vanilla is the quality of gears. 
Killing town patrols give enough equipment to siege a base, not to mention the power of static mg with thermal vision and 1km range.

Possible options:
A) play as indipendend and have FIA as opponents, NATO only for bases, airports and specops.
B) limit '50 ammo maybe with setVehicleAmmo to 30% into the vehinit
C) check and ask for APEX on startup to include gendarme replacing town patrols and adding AKs and RPG to Arsenal.
D) Import WotP revive system.

Open to other ideas.

**Comment by IrLED** [comment]
I'd abstain from putting the requirement on any premium content (paid DLC APEX etc). Items might appear, and player just won't use them (e.g. remote designator in ammo drop from Snipers) but not hard requirement.

**Comment by mnarijnm** [comment]
I agree with @IrLED.
My honest opinion is that option A is for now the most realistic option to balance vanilla. It would also fit more in the story of antistasi. NATO/themself hires people to guard there town's. And the really strategic places are guarded by stronger NATO forces.

**Comment by StefArma** [comment]
Then i need to understand how to enhance the template in that way

**Comment by StefArma** [comment]
This is how a patrol is created
https://github.com/A3Antistasi/antistasiofficial/blob/d2b5954240be8bd1afed244fe157e64cb7257b85/AntistasiOfficial.Altis/CREATE/createBase.sqf#L133-L134

--

infpatrol is a variable defined into Templates which looks tight to group usage because they require a cfgpath
https://github.com/A3Antistasi/antistasiofficial/blob/d2b5954240be8bd1afed244fe157e64cb7257b85/AntistasiOfficial.Altis/Templates/IND_AAF.sqf#L103-L108

--

there is a pick group function called where the relative cfg has to be used to define the path
https://github.com/A3Antistasi/antistasiofficial/blob/d2b5954240be8bd1afed244fe157e64cb7257b85/AntistasiOfficial.Altis/Functions/fn_pickGroup.sqf#L8-L13


In this system, i don't know how to add a cfginf2 when i wanna use FIA groups. 
Warlords of the Pacific code don't use those cfg anymore, looks way smoother and customizable but i don't know how to make it like that without breaking things.

**Comment by StefArma** [comment]
Unconsistent
