### ISSUE TITLE
ACE 3 Misc Items wrong location in arsenal

### ISSUE THREAD

**Issue by RHLier** [A3Antistasi/antistasiofficial#64]
All ACE misc items are missing from Misc tab. Instead they are located in Bipod tab for every weapon and cannot be retrieved that way.
ACE version 3.11.0.1
Tested on antistasi 1.7.16C and 1.7.16D(with updated ACE detection), with Jeroen arsenal on
![ar](https://user-images.githubusercontent.com/11831786/31999090-c31889da-b99a-11e7-8f7b-0b9932d37caf.png)

**Comment by StefArma** [comment]
Fireman linked me this https://github.com/acemod/ACE3/issues/5673

the problem is that i can't find InventoryItem_Base_F in antistasi to replace with CBA_MiscItem_ItemInfo as  the issue suggest...

**Comment by RHLier** [comment]
I've found this link:
https://github.com/CBATeam/CBA_A3/pull/744
I hope this will help.

**Comment by mnarijnm** [comment]
The ACE_items are on the wrong position because since ACE changed from mine detecting system > CBA_miscItem (for good reasons). But because of that the initializing of the arsenal is partly fucked. We need to figure out how the arsenal recognize the ACE items again and put them into the misc item section. This is the mainreason why the ACE items are not showing up when you start a new campaign. I think because we need to call the items on a different way. My guess would be that the trouble is in the: fn_detectACE.sqf

**Comment by IrLED** [comment]
Somehow ACE misc items are categorized as `AccessoryBipod`.
local debug console
```
diag_log  (["ACE_EntrenchingTool"] call bis_fnc_itemtype);
```
rpt
``` 
[""Item"",""AccessoryBipod""]
```
[fn_JNA_classifyItem.sqf](https://github.com/A3Antistasi/antistasiofficial/blob/master/AntistasiOfficial.Altis/Functions/fn_JNA_classifyItem.sqf#L52) classifies `AccessoryBipod` as `bipod`

That classification is [interpreted](https://github.com/A3Antistasi/antistasiofficial/blob/master/AntistasiOfficial.Altis/Functions/fn_JNA_setupGear.sqf#L24) to[ `jna_index_bipod` global var](https://github.com/A3Antistasi/antistasiofficial/blob/460678afdcf6304e329f41daf97966d78d29fb01/AntistasiOfficial.Altis/Lists/gearList.sqf#L1127)

The Arsenal data structure shows that items indeed are in that bipod category
```
diag_log (jna_dataList select jna_index_bipod);
```
imho that's the obvious bug from ACE items configuration, whether we adapt to it or wait for the fix.

**Comment by IrLED** [comment]
Is related to #60

**Comment by RHLier** [comment]
I think it's related to how CBA handles now an old ace 3 misc item class:
https://github.com/CBATeam/CBA_A3/blob/master/addons/common/CfgWeapons.hpp
line 5

**Comment by IrLED** [comment]
The case, when new items are delivered via AirDrop (with ACE misc items), was not covered by previous fix. PR pending

**Comment by StefArma** [comment]
also, when looking at rifle attatchments, arsenal displays medical stuff instead of bipods etc.
