### ISSUE TITLE
Lantern duplicating

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#66]
The optional cosmethic lantern is duplicating every time the game is loaded, 

ingamefix = Commander -> y menu -> Emplacements ->  HQ fortification -> remove all

**Comment by GlennMey** [comment]
This happens with boats aswell, so don't have your base close to a boat spawn. Or more precise don't have the boat spawn inside the 50m radius.

**Comment by eagledude4** [comment]
I noticed this as well. It gets hella-bright at night XD

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/commit/24575bd04f41206847fcff4e0e071daf83cbfe2a Fixed
