### ISSUE TITLE
CSAT punsihment fix

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#67]
Conditions looks quite ok, if you've captured too many bases then CSAT will think about destroying town.

The problem is they're not effective and mostly they aren't able to kill all civilians. 
So we need to rework the thing.

UPDATE solutions: 19/01
A) Fix the airdrop, sometime not working
B) Add reveal after a certain time so that the killing will happen anyway if no player is around

**Comment by JustSharkbait** [comment]
An all air assault seems awesome. Because it adds an element to show just how powerful CSAT and NATO is to remind the player they are just gorillas--while also allowing the player to counter it with enough AA.

**Comment by StefArma** [comment]
Ok, arcade idea from scratch:
- 4 napalm run: each successfull run reduce the civilians by 25% of that town and addthe amount into "killedciv"
- if "killedciv" rise above a certain number (1000?) the campaign is lost
- if x bombardaments fail then CSAT send ground forces to kill civilians (current script)

This means player managed to defend the area and there is sense to make them send units and we avoid units somewhere player can't reach.

**Comment by JustSharkbait** [comment]
That is an awesome idea.

**Comment by StefArma** [comment]
Another easier solutions is:
reveal the civilian to CSAT after a certain time to conclude the fight.

Everything looks working now apart those civilians are never found

**Comment by StefArma** [comment]
removed comments about my old idea, updated the current one that should be enough.. just need to code it

**Comment by StefArma** [comment]
It's working! still not so good as content but here it is

https://github.com/A3Antistasi/antistasiofficial/issues/219

**Comment by StefArma** [comment]
on server is running, we noticed that if there is a heavy load the delay of napalm damage last even a minute longer than it dropped causing players getting killed for apparent no reason.

The presence of players defending might make the attack easy by using simply a few AA rockets. 
Maybe a check on player AA around the area could make CSAT land far away and then come in on foot
