### ISSUE TITLE
JGS - Vehicles colliding in preview

### ISSUE THREAD

**Issue by DukeVenator** [A3Antistasi/antistasiofficial#7]
Need to improve the detection of objects for heli when previewing from garage as it finds a spot next to  a building and blow everything to kingdom kom

**Comment by AlexTriada** [comment]
May be this help:
 player setPosATL (getPosWorld player findEmptyPosition [1,5,"B_Soldier_02_F"]);

**Comment by AlexTriada** [comment]
This teleporting player to the empty position near

**Comment by loxley314** [comment]
I created this ticket again didn't find this one before to open mine:
https://github.com/A3Antistasi/antistasiofficial/issues/102

I wrote again a part of the other ticket, I think could be useful:

There are 2 commented lines currently in code. That 2 lines avoid this behaviour when are uncommented. Are only applied while a vehicle is previewed. 
https://github.com/A3Antistasi/antistasiofficial/blob/0cfebce208399ec2810cb16a47a5ddb3e422629a/AntistasiOfficial.Altis/JeroenArsenal/JNG/fn_garage.sqf#L1685-L1686

I tried to uncomment those lines on my server and works fine.

**Comment by StefArma** [comment]
If that's not causing anything else.. we can try it ofcourse! Good call loxley313

**Comment by loxley314** [comment]
I tried to spawn vehicle even after to know that what colliding with one object on scenario and it moved like 20 meters after clicking "get vehicle" button. Apart from that behaviour looks fine form me, I don't know why is commented.

**Comment by StefArma** [comment]
Testing https://github.com/A3Antistasi/antistasiofficial/commit/14e360dd005741d53cf09f10708f6df7d0a6c2a4
