### ISSUE TITLE
Saving of vehicles in HQ.

### ISSUE THREAD

**Issue by mahaera** [A3Antistasi/antistasiofficial#72]
Hi,
so during playing (SP) I've found a few couple annoying issues. This is one of them and how I fixed them. Hope this helps and that you can implement this.

Vehicles are not actually saved that are within 50m radius of HQ flag. Error is in wrong reference point (spawn marker) when checking how far vehicles are from the HQ to save them.
Need to change <.. "respawn_west" ..> to <.. guer_respawn ..> in file "/Save/fn_saveGame.sqf" line 169.
That line should be like this: <.. if (_vehicle distance getMarkerPos guer_respawn < 50) then { ..>
This is because "respawn_west" is not really used and doesn't reference to HQ position anymore (possibly refactoring error from the past).

For myself I've also changed distance from 50m to 100m and updated save message in "Stringtable.xml" line 1191. This particular is more realistic and satisfying to me.

https://github.com/A3Antistasi/antistasiofficial/issues/73

https://github.com/A3Antistasi/antistasiofficial/issues/74

**Comment by StefArma** [comment]
Would you mind create different issue post for each? that would be easier to handle :)

**Comment by mahaera** [comment]
Sure, in a min ;)

**Comment by StefArma** [comment]
Cheers!

**Comment by StefArma** [comment]
Uhmm i see vehicle are usually saved for me... then i haven't always checked because i tend to garage them all to avoid troubles. 

Gonna do better tests

**Comment by StefArma** [comment]
loss of evidences
