### ISSUE TITLE
Civilian pedestrian speed

### ISSUE THREAD

**Issue by mahaera** [A3Antistasi/antistasiofficial#73]
Hi,
so during playing (SP) I've found a few couple annoying issues. This is one of them and how I fixed them. Hope this helps and that you can implement this.

HR are not reimbursed during the persistent save from players squad members or HC squads. Fix is to remove <.. AND (_x getVariable ["generated",false]) ..> in <.. {(alive _x) AND (!isPlayer _x) AND (_x getVariable ["BLUFORSpawn",false]) AND (_x getVariable ["generated",false])} ..> in "/Save/fn_saveGame.sqf" line 51. That variable "generated" is not being set to the hired personnel therefore they're left out and not counted in. That line should be like this <.. _hr = (server getVariable ["hr",0]) + ({ (alive _x) AND (!isPlayer _x) AND (_x getVariable ["BLUFORSpawn",false]) } count allUnits); ..>

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/issues/46

uhmm i tried to merge theese but i'm pretty new to github

**Comment by mahaera** [comment]
I noticed this issue with pedestrian civilians basically. Them running all around the place all the time annoyed me. Need to check if their "Limited" speed influences their driving speed as well. Though for military AI units driving speed should depend on their combat alertness, theoretically.

**Comment by StefArma** [comment]
My concerns are civi vehicles which oftenly crash.. limited speed might reduce collateral damages.

Anyway i'm following your advice let's see what i can do
