### ISSUE TITLE
HR not reimbursed during save.

### ISSUE THREAD

**Issue by mahaera** [A3Antistasi/antistasiofficial#74]
Hi,
so during playing (SP) I've found a few couple annoying issues. This is one of them and how I fixed them. Hope this helps and that you can implement this.

Lame civilian starting speed (they end up with "normal" speed which causes them to run around all the time like idiots). Fixed them to start out with limited speed. Fix is in file "/CREATE/createCIV.sqf" line 85. Need to add "LIMITED" to the list of attributes. That line should be like this: <.. [leader _group, _marker, "SAFE", "LIMITED", "SPAWNED","NOFOLLOW", "NOVEH2","NOSHARE","DoRelax"] execVM "scripts\UPSMON.sqf"; ..>

**Comment by StefArma** [comment]
Fixed with a BIS update
