### ISSUE TITLE
Mission cooldown

### ISSUE THREAD

**Issue by RHLier** [A3Antistasi/antistasiofficial#77]
I've noticed that after you have finished or failed mission, Petros is still refusing to give a new mission of the same type from Mission Request menu (e.g. Propaganda) . For now, the only way to fix it is to restart the mission, respectively clearing the task list.

**Comment by StefArma** [comment]
Actually, each mission type has a cooldown... it make senses in some cases, in other cases i'm agree it has no sense. 

Maybe i point you to this topic: https://github.com/A3Antistasi/antistasiofficial/issues/49
