### ISSUE TITLE
Garrison duplication

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#78]
http://www.a3antistasi.com/forum/m/38173738/viewthread/31050403-duplicity-garrisons/post/133074030#p133074030

as projix state and show in his screenshot

**Comment by StefArma** [comment]
The possible places where the bug lies
https://github.com/A3Antistasi/antistasiofficial/blob/9d1efb5eec6345201eb1c5ac748199b768c4554c/AntistasiOfficial.Altis/CREATE/createNATOaerop.sqf#L337-L346

https://github.com/A3Antistasi/antistasiofficial/blob/9d1efb5eec6345201eb1c5ac748199b768c4554c/AntistasiOfficial.Altis/distancias3.sqf#L70-L92
For this second part I'm gonna check if before 1.7 there was the +50m to despawn which was a smart idea to avoid lagging when driving on the edge of a spawning radious. However it doesn't cause any bug to enemy so i'm also comparing the two spawning and see if something was added

**Comment by AlexTriada** [comment]
It's strange that you do not notice it, but there are more bots in the garrisons than the commander puts them. For example, I put 20 bots, and they appear 30-40. And you are still fighting for some kind of
performance.
This happens almost always, especially it is connected with bots - commanders

**Comment by IrLED** [comment]
Supposedly will be fixed by #141
>Friendly garrisons of types FIAresources FIApower NATOaerop NATObases FIAOutpost are affected by the duplication bug.
The reproduction of the bug:
friendly base with garrison greater then 8 men (mobile not static), but not of 8*X size. Best effect is for garrison of 15 men. Trigger the spawn by approaching the zone, observe the group of 8 ppl starting the patrol. The group of remaining units stays still wear default gear (e.g. F2000 assault rifles), and doesn't despawn when the zone is cleaned. Approaching-leaving the zone accumulates loitering AI units.

**Comment by headstone1990** [comment]
This bug still reproduce if you hire garrison when object area is cached(from Petros, player or other reason).

**Comment by StefArma** [comment]
Thanks for the report, infact i think we were investigating the duplication when player leave and enter the area while an AI is caching them.

**Comment by IrLED** [comment]
@headstone1990 , apparently there are several duplication bugs. My fix was related to incorrectly initialized, never despawning AIs.

**Comment by vodas3** [comment]
i am prity ssure it will be problem in this code:
`_tipo = _this select 0;

_coste = server getVariable _tipo;
_salir = false;

if (_tipo == guer_sol_UN) then
	{
	_coste = _coste + ([guer_stat_mortar] call vehiclePrice);
	};
`

**Comment by StefArma** [comment]
Maybe??? https://github.com/A3Antistasi/antistasiofficial/commit/37c1d62c6a2587a81e8890a639bb2a0333bbc24b crossfingers

**Comment by StefArma** [comment]
Done!!! 

Step to reproduce:

Teleport to base, capture it,
teleport hq = enemies despawn
Add garrison 
Teleport to base, and teleport the flag there, recruit 1 garrison = you have 3 units.

With this fix no longer happen!
