### ISSUE TITLE
Rework Civilian support and powerplant 

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#79]
Function explanation:
[%AAF,%FIA,_city] spawn AS_fnc_changeCitySupport;
[-1,0,_city] spawn AS_fnc_changeCitySupport; = -1% AAF , nothing changed in FIA

-------------------------

Civilian mind change in odd way sometime,

i'm going to resume all code which change town support in this issue and see what we can do to polish it a bit.

Civi casualties
https://github.com/A3Antistasi/antistasiofficial/blob/460678afdcf6304e329f41daf97966d78d29fb01/AntistasiOfficial.Altis/CREATE/CIVinit.sqf#L32-L42

---

FIA casualties
https://github.com/A3Antistasi/antistasiofficial/blob/506a8a6b58e92f6be0ff19d3bba6cef791631487/AntistasiOfficial.Altis/onPlayerRespawn.sqf#L21
https://github.com/A3Antistasi/antistasiofficial/blob/506a8a6b58e92f6be0ff19d3bba6cef791631487/AntistasiOfficial.Altis/Functions/fn_initialiseFIAUnit.sqf#L299

--

NATO casualties
https://github.com/A3Antistasi/antistasiofficial/blob/460678afdcf6304e329f41daf97966d78d29fb01/AntistasiOfficial.Altis/CREATE/NATOinit.sqf#L11
https://github.com/A3Antistasi/antistasiofficial/blob/460678afdcf6304e329f41daf97966d78d29fb01/AntistasiOfficial.Altis/CREATE/NATOinitCA.sqf#L21
https://github.com/A3Antistasi/antistasiofficial/blob/79e3ca52343649bfaa30ce8f8fbd6228c1ce051e/AntistasiOfficial.Altis/CREATE/NATOVEHinit.sqf#L17

----

Destroyed: NATO vehicle, AAF apc, AAF tank, CSAT heli
https://github.com/A3Antistasi/antistasiofficial/blob/11a4bd7c191f859f00cbdc60d1ef95cd31dd89ac/AntistasiOfficial.Altis/CREATE/VEHinit.sqf#L33
https://github.com/A3Antistasi/antistasiofficial/blob/11a4bd7c191f859f00cbdc60d1ef95cd31dd89ac/AntistasiOfficial.Altis/CREATE/VEHinit.sqf#L50

---

AAF vehicle destroy **is this interfering with the one above? need check**
https://github.com/A3Antistasi/antistasiofficial/blob/11a4bd7c191f859f00cbdc60d1ef95cd31dd89ac/AntistasiOfficial.Altis/CREATE/genVEHinit.sqf#L20
https://github.com/A3Antistasi/antistasiofficial/blob/11a4bd7c191f859f00cbdc60d1ef95cd31dd89ac/AntistasiOfficial.Altis/CREATE/genVEHinit.sqf#L32

---

AAF unit casualties
https://github.com/A3Antistasi/antistasiofficial/blob/506a8a6b58e92f6be0ff19d3bba6cef791631487/AntistasiOfficial.Altis/AI/AAFKilledEH.sqf#L37
https://github.com/A3Antistasi/antistasiofficial/blob/506a8a6b58e92f6be0ff19d3bba6cef791631487/AntistasiOfficial.Altis/AI/AAFKilledEH.sqf#L43

---

Surrenders
https://github.com/A3Antistasi/antistasiofficial/blob/79e3ca52343649bfaa30ce8f8fbd6228c1ce051e/AntistasiOfficial.Altis/AI/capturar.sqf#L35
https://github.com/A3Antistasi/antistasiofficial/blob/460678afdcf6304e329f41daf97966d78d29fb01/AntistasiOfficial.Altis/AI/surrenderAction.sqf#L13
https://github.com/A3Antistasi/antistasiofficial/blob/460678afdcf6304e329f41daf97966d78d29fb01/AntistasiOfficial.Altis/AI/surrenderAction.sqf#L19

---

CSAT vehicle destroy. **Not agree**
https://github.com/A3Antistasi/antistasiofficial/blob/460678afdcf6304e329f41daf97966d78d29fb01/AntistasiOfficial.Altis/CREATE/CSATVEHinit.sqf#L20

---

Rebuilding **It's a lot**
https://github.com/A3Antistasi/antistasiofficial/blob/460678afdcf6304e329f41daf97966d78d29fb01/AntistasiOfficial.Altis/rebuildAssets.sqf#L31

Reward capturing territory when mission is triggered
+5% town support (many files useless to link)

Loosing marker **Not agree**
https://github.com/A3Antistasi/antistasiofficial/blob/460678afdcf6304e329f41daf97966d78d29fb01/AntistasiOfficial.Altis/mrkLOOSE.sqf#L38

Capturing marker
https://github.com/A3Antistasi/antistasiofficial/blob/11a4bd7c191f859f00cbdc60d1ef95cd31dd89ac/AntistasiOfficial.Altis/mrkWIN.sqf#L72

When building 
https://github.com/A3Antistasi/antistasiofficial/blob/460678afdcf6304e329f41daf97966d78d29fb01/AntistasiOfficial.Altis/CREATE/createAAsite.sqf#L98
https://github.com/A3Antistasi/antistasiofficial/blob/460678afdcf6304e329f41daf97966d78d29fb01/AntistasiOfficial.Altis/CREATE/createFIAEmplacement.sqf#L68
https://github.com/A3Antistasi/antistasiofficial/blob/460678afdcf6304e329f41daf97966d78d29fb01/AntistasiOfficial.Altis/CREATE/createWatchpost.sqf#L87

-----------------------------------------------------------------------
-----------------------------------------------------------------------

About powerplants the mechanic is difficult to understand so i'm thinking about hintscreen which tell the effect of taking a powerplant. 

This is how power influence
https://github.com/A3Antistasi/antistasiofficial/blob/460678afdcf6304e329f41daf97966d78d29fb01/AntistasiOfficial.Altis/resourcecheck.sqf#L82-L102

**Comment by StefArma** [comment]
http://a3antistasi.enjin.com/forum/m/38173738/viewthread/29560783-requested-change-cap-enemy-city-support-gain-from-control-local-power-plant/post/134704077#p134704077 reference

**Comment by StefArma** [comment]
i tought it simpler...

low - medium - good

when they're on low or medium, bringing the relative crate (there are available 3 kind of crates in IDAP dlc) it will increase by 1 tier, that's it

**Comment by wurzel0701** [comment]
Ok, how should it decrease? Like every tick one tier or several ticks for a tier?
Several will be more work but doable. And will this be the same for all cities?

**Comment by StefArma** [comment]
on resourcecheck (game tick) there is a random update on civilians need. 
Let's say 3 town can decrease of one specific need, so every game tick is an opportunity for player to help a town.

No bad consequences if levels are low, they take happily what you give, without complain :)

**Comment by wurzel0701** [comment]
Ok no consequences, and every tick three random town will lose one tier of a random supply, do I got this right?

**Comment by StefArma** [comment]
within the 4km from HQ as usual for other missions

**Comment by StefArma** [comment]
Let AAF send goods, not important yet

I wanna rework the mission system: supplies can appear at HQ, but can also be found.. still deciding where, maybe to seaports or certain buildigs like the big storage ones with big door and maybe spawn in few soldiers + the supplycrate...

so if player find those crate, can load them on the truck and just bring them to a town that need those supplies.

AAF won't destroy goods, they'll just try to kill you if they see you doing it.


wait... by "DONE" you mean you're coding it?

**Comment by wurzel0701** [comment]
> wait... by "DONE" you mean you're coding it?
Yeah kind of, I was playing arund a bit, but if you want to do this alone, I will search for another issue that looks interesting.

**Comment by StefArma** [comment]
noo! i'm actually super happy about that! very looking forward to see your stuff ;)

**Comment by StefArma** [comment]
as i said in the roadmap i'm actually on a break from coding, and one reason is that i was alone

**Comment by StefArma** [comment]
Indeed, have you a branch of this so i can see the code? we can meet on TS for details

Uhmm so far we kept it arcade.. and that's why i introduced the boxex.. before it was a truck, explode the truck = fail.

**Comment by StefArma** [comment]
got it, i'll take a look now i've to study, thanks a lot!

**Comment by StefArma** [comment]
Let's continue here https://github.com/A3Antistasi/antistasiofficial/pull/313/files

**Comment by wurzel0701** [comment]
Supply system done. Maybe its time to close this issue @StefArma
