### ISSUE TITLE
Air control

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/antistasiofficial#80]
Regardless the fact people can steal aircraft too easy, there is a lot of action missing just because of some poor scritp.

Enhancements:
A) Make a specific rule in spawn distance that make spawned in AA truck on hilltrops and 1 AA soldier on each AA outpost. within 4 km from a FIA aircraft
B) FIA Aircraft hitting a militarized objective trigger 1 enemy jet taking off from closest airport 

Here's the pull request https://github.com/A3Antistasi/antistasiofficial/pull/134

**Comment by FlyingVolvo** [comment]
Perhaps forcing first person in certain kinds of vehicle classes like tanks, jets, and helicopters, would help alleviate this spam? I know we discussed this earlier on a few occasions, but I'm unsure if you made any progress on it. This would also, without putting up a hard barrier (such as locking vehicles with no way to unlock them), require people turning out in tanks for better visibility, and exposing themselves to being taken out by infantry if they aren't careful, also no 180 degrees of visibility.

Commander role in tanks would also have a function. I think this is a much better idea then implementing a hard barrier to preventing the spam from occuring, at least in theory.

**Comment by StefArma** [comment]
No, that mean forcing people on how to play which is bad.

I wanna give options, not limits.

**Comment by IrLED** [comment]
If people want to fly/drive heavy machines - why not. But rearming shouldn't be cheap/free, only unlimited ammo for unlimited weapons. The same should go to ammo trucks (and my beloved mortars). Also flying-driving beyond front-line shouldn't be so easy, spawn random rocket (even without actual AI unit) to make life of those miserable

**Comment by ckhawks** [comment]
I feel like I'm pretty bad at this gamemode in general, but I don't see how stealing air vehicles is easy?

**Comment by StefArma** [comment]
Visit official server and you'll realize :) 
steam://connect/85.190.158.136:29001

**Comment by StefArma** [comment]
Actually and RHS AFRF anti air vehicle rhs_zsu234_aa with 100% skill and 100% gamedifficulty  in a blank mission in VR manage to see me 1,5 km away.

With "this reveal [player,4]" he see me at any distance, shoot me, but keep missing untill i'm 1,2 km away.

**Comment by ckhawks** [comment]
Yeah, AI is pretty op. I basically exclusively play vanilla, so I haven't
particularly experienced RHS behavior but I would assume it's similar.

**Comment by StefArma** [comment]
sorry i was saying range is too close to be effective :(

**Comment by StefArma** [comment]
https://github.com/A3Antistasi/antistasiofficial/pull/134

**Comment by VenomSnake1985** [comment]
Well in my opinion the AA outposts are incredibly easy to assault in a helicopter.

I've flown in multiple groups of players to an LZ nearby an AA outpost in an overt helicopter without even getting locked on.

Even though I shouldn't be flying anywhere near an AA outpost I'm able to land troops very close to them.

**Comment by StefArma** [comment]
It's almost done!! Continue here https://github.com/A3Antistasi/antistasiofficial/pull/322

**Comment by zalexki** [comment]
don't close if not properly done and tested
