### ISSUE TITLE
Fast-travel with AI in second vehicle causes two vehicles spawn at the same place

### ISSUE THREAD

**Issue by IrLED** [A3Antistasi/antistasiofficial#91]
Copied from [official forum](http://www.a3antistasi.com/forum/m/38173738/viewthread/31172874-destroyed-vehicles-at-base-sellable-infinite-amount-times)
**Tali**
>If I control a vehicle, and have AI in another vehicle then I Fast travel back to base. We spawned in each other and everything went up in fireworks.

**Comment by StefArma** [comment]
https://github.com/LordGolias/antistasi/commit/872a6990017ec335f903f6b2428fbb8ec1a23484

**Comment by StefArma** [comment]
should be fixed
