### ISSUE TITLE
Slowdown upon adding items quickly using JAS

### ISSUE THREAD

**Issue by FlyingVolvo** [A3Antistasi/antistasiofficial#95]
There is significant slowdown when rapidly adding items or removing things to your inventory using the JAS. This can easily be reproduced by adding bandages or some other item to or from your inventory in a rapid succession.

This is a minor issue, since it's only a issue when inside of the arsenal, and doesn't effect performance outside it.

**Comment by StefArma** [comment]
Fixed by Barbolani https://github.com/A3Antistasi/antistasiofficial/commit/aaee9632a66a7cdbdc7c79f4c526267b8dba0826
